<?php
$translations = [
    'ar' => [
        'site_name' => 'نظام إدارة الموظفين',
        'login' => 'تسجيل الدخول',
        'logout' => 'تسجيل الخروج',
        'username' => 'اسم المستخدم',
        'password' => 'كلمة المرور',
        'email' => 'البريد الإلكتروني',
        'role' => 'الصلاحية',
        'dashboard' => 'لوحة التحكم',
        'employees' => 'إدارة الموظفين',
        'approvals' => 'طلبات الاعتماد',
        'leaves' => 'إدارة الإجازات',
        'my_profile' => 'ملفي الشخصي',
        'my_requests' => 'طلباتي',
        'system_users' => 'مستخدمي النظام',
        'departments' => 'إدارة الأقسام',
        'leave_types' => 'أنواع الإجازات',
        'welcome' => 'مرحباً',
        'total_employees' => 'إجمالي الموظفين',
        'pending_approvals' => 'بانتظار الاعتماد',
        'pending_leaves' => 'إجازات معلقة',
        'approved_leaves' => 'إجازات مقبولة',
        'my_pending_leaves' => 'إجازاتي المعلقة',
        'my_approved_leaves' => 'إجازاتي المقبولة',
        'add_new' => 'إضافة جديد',
        'edit' => 'تعديل',
        'delete' => 'حذف',
        'save' => 'حفظ التغييرات',
        'cancel' => 'إلغاء',
        'actions' => 'الإجراءات',
        'status' => 'الحالة',
        'full_name' => 'الاسم الكامل',
        'phone' => 'رقم الجوال',
        'job_title' => 'المسمى الوظيفي',
        'hire_date' => 'تاريخ التوظيف',
        'department' => 'القسم',
        'employee_id' => 'الرقم الوظيفي',
        'pending' => 'معلق',
        'approved' => 'معتمد',
        'rejected' => 'مرفوض',
        'reason' => 'السبب',
        'notes' => 'ملاحظات المدير',
        'start_date' => 'تاريخ البداية',
        'end_date' => 'تاريخ النهاية',
        'duration' => 'المدة',
        'days' => 'أيام',
        'submit' => 'إرسال',
        'close' => 'إغلاق',
        'error_login' => 'اسم المستخدم أو كلمة المرور غير صحيحة.',
        'success_added' => 'تمت الإضافة بنجاح.',
        'success_updated' => 'تم التحديث بنجاح.',
        'success_deleted' => 'تمت عملية الحذف بنجاح.',
        'confirm_delete' => 'هل أنت متأكد من الحذف؟',
        'no_data' => 'لا توجد بيانات حالياً.',
        'view' => 'عرض',
        'details' => 'التفاصيل',
        'account_info' => 'بيانات الحساب',
        'basic_info' => 'البيانات الأساسية',
        'rejection_reason' => 'سبب الرفض',
        'decision_date' => 'تاريخ القرار',
        'approve' => 'موافقة',
        'reject' => 'رفض',
        'leave_details' => 'تفاصيل الإجازة',
        'new_request' => 'طلب جديد',
        'manager_note' => 'ملاحظة المدير',
        'add_department' => 'إضافة قسم',
        'edit_department' => 'تعديل قسم',
        'dept_name' => 'اسم القسم (عربي)',
        'dept_name_en' => 'اسم القسم (EN)',
        'add_leave_type' => 'إضافة نوع إجازة',
        'edit_leave_type' => 'تعديل نوع إجازة',
        'type_name' => 'مسمى الإجازة (عربي)',
        'type_name_en' => 'مسمى الإجازة (EN)',
        'user_management' => 'إدارة المستخدمين',
        'add_user' => 'إضافة مستخدم',
        'admin' => 'مدير نظام',
        'manager' => 'مدير',
        'employee' => 'موظف',
        'db_error' => 'خطأ في الاتصال بقاعدة البيانات',
        'error_generic' => 'خطأ',
        'access_denied' => 'عذراً، ليس لديك صلاحية للوصول إلى هذه الصفحة.',
        'register' => 'طلب تسجيل جديد',
        'already_have_account' => 'لديك حساب بالفعل؟',
        'dont_have_account' => 'هل أنت موظف؟',
        'registration_success' => 'تم تقديم طلب التسجيل بنجاح، يرجى انتظار اعتماد الإدارة. تابع بريدك الإلكتروني (بما في ذلك البريد المزعج) لرسالة التحقق.',
        'all_rights' => 'حقوق النشر محفوظة',
        'top_leave_types' => 'أكثر أنواع الإجازات طلباً',
        'top_employees_leaves' => 'الموظفين الأكثر طلباً للإجازات',
        'requests' => 'طلبات',
        'leave_stats' => 'إحصائيات الإجازات',
        'monthly_requests' => 'الطلبات الشهرية',
        'approved_vs_rejected' => 'المقبولة مقابل المرفوضة',
        'system_id' => 'معرف النظام',
        'initial_balance' => 'رصيد الإجازات الحالي',
        'balance_verified' => 'تم تأكيد الرصيد',
        'operation_code' => 'كود العملية',
        'operation_time' => 'وقت العملية',
        'verify_balance' => 'تأكيد رصيد الإجازات',
        'language' => '🇬🇧',
        'notifications' => 'الإشعارات',
        'mark_as_read' => 'تحديد كمقروء',
        'no_notifications' => 'لا توجد إشعارات جديدة',
        'new_leave_request' => 'طلب إجازة جديد من',
        'leave_request_approved' => 'تمت الموافقة على طلب إجازتك',
        'leave_request_rejected' => 'تم رفض طلب إجازتك',
        'profile_approved' => 'تم اعتماد ملفك الوظيفي، يمكنك الآن استخدام النظام بالكامل',
        'profile_rejected' => 'تم رفض ملفك الوظيفي',
        'activity_log' => 'سجل النشاطات',
        'action' => 'الإجراء',
        'ip_address' => 'عنوان IP',
        'user_agent' => 'المتصفح/النظام',
        'time' => 'الوقت',
        'settings' => 'الإعدادات',
        'general_settings' => 'الإعدادات العامة',
        'ui_settings' => 'إعدادات الواجهة',
        'functional_settings' => 'الإعدادات الوظيفية',
        'primary_color' => 'اللون الأساسي',
        'font_family' => 'نوع الخط',
        'allow_registration' => 'تفعيل التسجيل',
        'allow_leave_requests' => 'تفعيل طلب الإجازات (للجميع)',
        'footer_text' => 'نص الفوتر',
        'on' => 'تشغيل',
        'off' => 'إيقاف',
        'save_settings' => 'حفظ الإعدادات',
        'registration_disabled' => 'عذراً، التسجيل متوقف حالياً.',
        'leave_requests_disabled' => 'عذراً، طلب الإجازات متوقف حالياً.',
        'leave_requests_disabled_for_you' => 'عذراً، لقد تم إيقاف صلاحية طلب الإجازات لحسابك مؤقتاً.',
        'balance_not_verified_error' => 'لا يمكنك تقديم طلب إجازة حتى يتم تسجيل رصيدك وتأكيده من قبل المدير.',
        'leave_days_count' => 'عدد أيام الإجازة',
        'security_note_balance' => 'ملاحظة أمان: لا يمكن تعديل الرصيد المعتمد إلا من قبل المدير.',
        'manager_only_fields' => 'بيانات يتحكم بها المدير فقط',
        'deduct_from_balance' => 'يخصم من الرصيد',
        'max_days_per_year' => 'الحد الأقصى (سنوياً)',
        'yes' => 'نعم',
        'no' => 'لا',
        'insufficient_balance' => 'رصيدك الحالي غير كافٍ لطلب هذه الإجازة.',
        'max_days_per_year_error' => 'تجاوزت الحد الأقصى المسموح به لهذه الإجازة',
        'dir' => 'rtl',
        
        'employee_not_found' => 'الموظف غير موجود.',
        'per_type' => '(لكل نوع)',
        'initial_balances_per_type' => 'رصيد الإجازات المبدئي (لكل نوع)',
        'initial_leave_balances' => 'أرصدة الإجازات المبدئية',
        'ensure_balance_verified' => 'يرجى التأكد من تسجيل رصيد الإجازات في ملفك الشخصي وانتظار اعتماد المدير.',
        'calendar_days' => 'أيام تقويمية',
        'total_balance' => 'إجمالي الرصيد',
        'enter_balance_accurately' => 'يرجى إدخال رصيدك الحالي بدقة لكل نوع، سيتم التحقق منه من قبل الإدارة.',
        'balance_details' => 'تفاصيل الأرصدة',
        'can_edit_balance_before_verification' => 'يمكنك تعديل رصيدك الأولي من خلال زر التعديل أعلاه قبل أن يتم تأكيده من الإدارة.',
        
        'you_have_total' => 'لديك رصيد إجازات إجمالي يبلغ',
        'days_of_leave' => 'يوم',
        'distributed_as_follows' => 'وهي مقسمة حسب الأنواع كالتالي',
        
        'request_dates' => 'تواريخ الطلب',
        'submitted_on' => 'وقت التقديم',
        'decided_on' => 'وقت القرار',
        
        'search_by_employee' => 'بحث بالموظف',
        'employee_name_or_id' => 'اسم أو رقم وظيفي',
        'leave_status' => 'حالة الطلب',
        'all' => 'الكل',
        'filter_btn' => 'تصفية',
        'export_excel' => 'تصدير إكسل',
        'leave_type_label' => 'نوع الإجازة',
        'global_search' => 'بحث شامل',
        'search_placeholder' => 'الاسم، الرقم الوظيفي، أو المعرف',
        'account_status' => 'حالة الحساب',
        'switch_org_desc' => 'يمكنك اختيار وتحديد جهة العمل النشطة من القائمة العلوية لإدارة موظفيها، إجازاتها، وإعداداتها بالكامل وكأنك رئيسها التنفيذي!',
        'quick_actions_center' => 'مركز الإجراءات السريعة (طلبات الإجازة المعلقة)',
        'needs_decision' => 'طلبات تحتاج اتخاذ قرار',
        'employee_label' => 'الموظف',
        'leave_dates' => 'تاريخ الإجازة',
        'work_days' => 'أيام العمل',
        'manager_note_optional' => 'ملاحظة المدير (اختياري)',
        'write_note' => 'اكتب ملاحظة...',
        'quick_decision' => 'اتخاذ قرار فوري',
        'all_departments' => 'جميع الأقسام',
        'lang_code' => 'ar'
    ],
    'en' => [
        'switch_org_desc' => 'You can select and switch active organizations from the top menu to manage their employees, leaves, and settings completely as if you were their CEO!',
        'quick_actions_center' => 'Quick Actions Center (Pending Leave Requests)',
        'needs_decision' => 'requests need a decision',
        'employee_label' => 'Employee',
        'leave_dates' => 'Leave Dates',
        'work_days' => 'Work Days',
        'manager_note_optional' => 'Manager Note (Optional)',
        'write_note' => 'Write a note...',
        'quick_decision' => 'Quick Decision',
        'db_error' => 'Database Connection Error',
        'error_generic' => 'Error',
        'access_denied' => 'Sorry, you do not have permission to access this page.',
        'register' => 'Request Registration',
        'already_have_account' => 'Already have an account?',
        'dont_have_account' => "Are you an employee?",
        'registration_success' => 'Registration request submitted successfully, please wait for management approval. Check your email (including Spam/Junk) for verification.',
        'all_rights' => 'All Rights Reserved',
        'top_leave_types' => 'Most Requested Leave Types',
        'top_employees_leaves' => 'Top Employees by Leave Requests',
        'requests' => 'Requests',
        'leave_stats' => 'Leave Statistics',
        'monthly_requests' => 'Monthly Requests',
        'approved_vs_rejected' => 'Approved vs Rejected',
        'language' => '🇸🇦',
        'notifications' => 'Notifications',
        'mark_as_read' => 'Mark as Read',
        'no_notifications' => 'No new notifications',
        'new_leave_request' => 'New leave request from',
        'leave_request_approved' => 'Your leave request has been approved',
        'leave_request_rejected' => 'Your leave request has been rejected',
        'profile_approved' => 'Your profile has been approved, you can now use the system',
        'profile_rejected' => 'Your profile has been rejected',
        'activity_log' => 'Activity Log',
        'action' => 'Action',
        'ip_address' => 'IP Address',
        'user_agent' => 'Browser/OS',
        'time' => 'Time',
        'site_name' => 'HR Management System',
        'login' => 'Login',
        'logout' => 'Logout',
        'username' => 'Username',
        'password' => 'Password',
        'email' => 'Email',
        'role' => 'Role',
        'dashboard' => 'Dashboard',
        'employees' => 'Employees Management',
        'approvals' => 'Approval Requests',
        'leaves' => 'Leave Management',
        'my_profile' => 'My Profile',
        'my_requests' => 'My Requests',
        'system_users' => 'System Users',
        'departments' => 'Departments',
        'leave_types' => 'Leave Types',
        'welcome' => 'Welcome',
        'total_employees' => 'Total Employees',
        'pending_approvals' => 'Pending Approvals',
        'pending_leaves' => 'Pending Leaves',
        'approved_leaves' => 'Approved Leaves',
        'my_pending_leaves' => 'My Pending Leaves',
        'my_approved_leaves' => 'My Approved Leaves',
        'add_new' => 'Add New',
        'edit' => 'Edit',
        'delete' => 'Delete',
        'save' => 'Save Changes',
        'cancel' => 'Cancel',
        'actions' => 'Actions',
        'status' => 'Status',
        'full_name' => 'Full Name',
        'phone' => 'Phone',
        'job_title' => 'Job Title',
        'hire_date' => 'Hire Date',
        'department' => 'Department',
        'employee_id' => 'Employee ID',
        'pending' => 'Pending',
        'approved' => 'Approved',
        'rejected' => 'Rejected',
        'reason' => 'Reason',
        'notes' => 'Manager Notes',
        'start_date' => 'Start Date',
        'end_date' => 'End Date',
        'duration' => 'Duration',
        'days' => 'Days',
        'submit' => 'Submit',
        'close' => 'Close',
        'error_login' => 'Invalid username or password.',
        'success_added' => 'Added successfully.',
        'success_updated' => 'Updated successfully.',
        'success_deleted' => 'Deleted successfully.',
        'confirm_delete' => 'Are you sure you want to delete?',
        'no_data' => 'No data found.',
        'view' => 'View',
        'details' => 'Details',
        'account_info' => 'Account Info',
        'basic_info' => 'Basic Info',
        'rejection_reason' => 'Rejection Reason',
        'decision_date' => 'Decision Date',
        'approve' => 'Approve',
        'reject' => 'Reject',
        'leave_details' => 'Leave Details',
        'new_request' => 'New Request',
        'manager_note' => 'Manager Note',
        'dept_name' => 'Dept Name (AR)',
        'dept_name_en' => 'Dept Name (EN)',
        'add_department' => 'Add Department',
        'edit_department' => 'Edit Department',
        'add_leave_type' => 'Add Leave Type',
        'edit_leave_type' => 'Edit Leave Type',
        'type_name' => 'Type Name (AR)',
        'type_name_en' => 'Type Name (EN)',
        'user_management' => 'User Management',
        'add_user' => 'Add User',
        'admin' => 'Admin',
        'manager' => 'Manager',
        'employee' => 'Employee',
        'system_id' => 'System ID',
        'initial_balance' => 'Current Leave Balance',
        'balance_verified' => 'Balance Verified',
        'operation_code' => 'Operation Code',
        'operation_time' => 'Operation Time',
        'verify_balance' => 'Verify Leave Balance',
        'settings' => 'Settings',
        'general_settings' => 'General Settings',
        'ui_settings' => 'UI Settings',
        'functional_settings' => 'Functional Settings',
        'primary_color' => 'Primary Color',
        'font_family' => 'Font Family',
        'allow_registration' => 'Enable Registration',
        'allow_leave_requests' => 'Enable Leave Requests (Global)',
        'footer_text' => 'Footer Text',
        'on' => 'ON',
        'off' => 'OFF',
        'save_settings' => 'Save Settings',
        'registration_disabled' => 'Sorry, registration is currently disabled.',
        'leave_requests_disabled' => 'Sorry, leave requests are currently disabled.',
        'leave_requests_disabled_for_you' => 'Sorry, leave requests are temporarily disabled for your account.',
        'balance_not_verified_error' => 'You cannot request leave until your balance is recorded and verified by the manager.',
        'leave_days_count' => 'Number of Leave Days',
        'security_note_balance' => 'Security Note: Verified balance can only be changed by manager.',
        'manager_only_fields' => 'Fields managed by Manager only',
        'deduct_from_balance' => 'Deduct from Balance',
        'max_days_per_year' => 'Max Days (Yearly)',
        'yes' => 'Yes',
        'no' => 'No',
        'insufficient_balance' => 'Your current balance is insufficient for this request.',
        'max_days_per_year_error' => 'Exceeded the maximum allowed days for this leave type',
        'dir' => 'ltr',
        
        'employee_not_found' => 'Employee not found.',
        'per_type' => '(Per Type)',
        'initial_balances_per_type' => 'Initial Leave Balances (Per Type)',
        'initial_leave_balances' => 'Initial Leave Balances',
        'ensure_balance_verified' => 'Please ensure your leave balance is recorded in your profile and verified by the manager.',
        'calendar_days' => 'Calendar Days',
        'total_balance' => 'Total Balance',
        'enter_balance_accurately' => 'Please enter your current balance accurately for each type; it will be verified by administration.',
        'balance_details' => 'Balance Details',
        'can_edit_balance_before_verification' => 'You can edit your initial balance using the edit button above before it is verified by administration.',
        
        'you_have_total' => 'You have a total leave balance of',
        'days_of_leave' => 'days',
        'distributed_as_follows' => 'distributed by type as follows',
        
        'request_dates' => 'Request Dates',
        'submitted_on' => 'Submitted On',
        'decided_on' => 'Decided On',
        
        'search_by_employee' => 'Search by Employee',
        'employee_name_or_id' => 'Name or ID',
        'leave_status' => 'Leave Status',
        'all' => 'All',
        'filter_btn' => 'Filter',
        'export_excel' => 'Export Excel',
        'leave_type_label' => 'Leave Type',
        'global_search' => 'Global Search',
        'search_placeholder' => 'Name, ID, or System ID',
        'account_status' => 'Account Status',
        'all_departments' => 'All Departments',
        'lang_code' => 'en'
    ]
];

$translations['ar']['prevent_overlapping_leaves'] = 'منع تداخل الإجازات';
$translations['en']['prevent_overlapping_leaves'] = 'Prevent Overlapping Leaves';
$translations['ar']['allow_past_leaves'] = 'السماح بتقديم إجازة بأثر رجعي (تواريخ سابقة)';
$translations['en']['allow_past_leaves'] = 'Allow Retroactive Leaves (Past Dates)';
$translations['ar']['past_leaves_error'] = 'عذراً، غير مسموح بتقديم طلب إجازة في تاريخ قد مضى.';
$translations['en']['past_leaves_error'] = 'Sorry, requesting a leave in the past is not allowed.';

// Settings titles
$translations['ar']['leave_controls'] = 'ضوابط وأنظمة الإجازات';
$translations['en']['leave_controls'] = 'Leave Policies & Controls';

$translations['ar']['overlapping_leaves_error'] = 'عذراً، يوجد لديك إجازة سابقة (معلقة أو مقبولة) تتداخل مع هذه التواريخ.';
$translations['en']['overlapping_leaves_error'] = 'Sorry, you have a previous leave (pending or approved) that overlaps with these dates.';

// 2FA translations
$translations['ar']['security_settings'] = 'إعدادات الأمان';
$translations['en']['security_settings'] = 'Security Settings';
$translations['ar']['2fa_title'] = 'التحقق الثنائي باستخدام تطبيق (2FA)';
$translations['en']['2fa_title'] = 'Two-Factor Authentication (2FA)';
$translations['ar']['2fa_active_title'] = 'ميزة التحقق الثنائي نشطة حالياً لحماية حسابك!';
$translations['en']['2fa_active_title'] = 'Two-Factor Authentication is currently active!';
$translations['ar']['2fa_active_desc'] = 'في كل مرة تقوم فيها بتسجيل الدخول، سيُطلب منك إدخال رمز التحقق المكون من 6 أرقام من تطبيق Authenticator الخاص بك.';
$translations['en']['2fa_active_desc'] = 'Each time you login, you will be required to enter the 6-digit verification code from your Authenticator app.';
$translations['ar']['2fa_disable_title'] = 'تعطيل التحقق الثنائي';
$translations['en']['2fa_disable_title'] = 'Disable Two-Factor Authentication';
$translations['ar']['2fa_disable_desc'] = 'لتعطيل هذه الميزة الأمنية، يرجى إدخال الرمز الحالي من تطبيق التحقق للـتأكيد:';
$translations['en']['2fa_disable_desc'] = 'To disable this security feature, please enter the current code from your Authenticator app to confirm:';
$translations['ar']['2fa_disable_btn'] = 'تعطيل التحقق الثنائي';
$translations['en']['2fa_disable_btn'] = 'Disable Two-Factor Authentication';
$translations['ar']['2fa_enable_btn'] = 'تفعيل التحقق الثنائي';
$translations['en']['2fa_enable_btn'] = 'Enable Two-Factor Authentication';
$translations['ar']['2fa_enabled_success'] = 'تم تفعيل ميزة التحقق الثنائي بنجاح وحماية حسابك!';
$translations['en']['2fa_enabled_success'] = 'Two-factor authentication enabled successfully!';
$translations['ar']['2fa_disabled_success'] = 'تم تعطيل التحقق الثنائي بنجاح. حسابك الآن أقل أماناً.';
$translations['en']['2fa_disabled_success'] = 'Two-factor authentication disabled successfully.';
$translations['ar']['2fa_invalid_code'] = 'الرمز المدخل غير صحيح أو انتهت صلاحيته الزمنيّة، يرجى المحاولة مجدداً.';
$translations['en']['2fa_invalid_code'] = 'Invalid verification code, please try again.';

// Super Admin translations
$translations['ar']['super_admin_dashboard'] = 'لوحة تحكم المدير العام';
$translations['en']['super_admin_dashboard'] = 'Super Admin Dashboard';
$translations['ar']['organizations_mgmt'] = 'إدارة جهات العمل';
$translations['en']['organizations_mgmt'] = 'Organizations Management';
$translations['ar']['add_organization'] = 'إضافة جهة عمل جديدة';
$translations['en']['add_organization'] = 'Add New Organization';
$translations['ar']['edit_organization'] = 'تعديل جهة العمل';
$translations['en']['edit_organization'] = 'Edit Organization';
$translations['ar']['org_name_ar'] = 'اسم جهة العمل (عربي)';
$translations['en']['org_name_ar'] = 'Organization Name (Arabic)';
$translations['ar']['org_name_ar_example'] = 'مثال: مستشفى التخصصي';
$translations['en']['org_name_ar_example'] = 'e.g. Specialty Hospital';
$translations['ar']['org_name_en'] = 'اسم جهة العمل (EN)';
$translations['en']['org_name_en'] = 'Organization Name (English)';
$translations['ar']['org_name_en_example'] = 'مثال: وزارة التعليم';
$translations['en']['org_name_en_example'] = 'e.g. Ministry of Education';
$translations['ar']['org_slug'] = 'معرف جهة العمل الفريد (Slug)';
$translations['en']['org_slug'] = 'Organization Slug (Unique Key)';
$translations['ar']['org_slug_example'] = 'مثال: ministry-of-education';
$translations['en']['org_slug_example'] = 'e.g. ministry-of-education';
$translations['ar']['org_manager_username'] = 'اسم مستخدم المدير المشرف';
$translations['en']['org_manager_username'] = 'Supervising Manager Username';
$translations['ar']['org_manager_email'] = 'البريد الإلكتروني للمدير';
$translations['en']['org_manager_email'] = 'Manager Email Address';
$translations['ar']['org_manager_password'] = 'كلمة مرور المدير الأولى';
$translations['en']['org_manager_password'] = 'Initial Manager Password';
$translations['ar']['active'] = 'نشط';
$translations['en']['active'] = 'Active';
$translations['ar']['suspended'] = 'معطل';
$translations['en']['suspended'] = 'Suspended';
$translations['ar']['all_organizations'] = 'جميع جهات العمل';
$translations['en']['all_organizations'] = 'All Organizations';
$translations['ar']['org_count'] = 'عدد جهات العمل';
$translations['en']['org_count'] = 'Organizations Count';
$translations['ar']['organization'] = 'جهة العمل';
$translations['en']['organization'] = 'Organization';
$translations['ar']['switch_org'] = 'تغيير جهة العمل النشطة';
$translations['en']['switch_org'] = 'Switch Active Organization';
$translations['ar']['success_org_created'] = 'تم إنشاء جهة العمل وحساب المدير بنجاح!';
$translations['en']['success_org_created'] = 'Organization and manager account created successfully!';

// Weekend & Holidays & Reports Translations
$translations['ar']['weekend_settings'] = 'إعدادات عطلات نهاية الأسبوع';
$translations['en']['weekend_settings'] = 'Weekend Settings';
$translations['ar']['weekend_days'] = 'أيام نهاية الأسبوع';
$translations['en']['weekend_days'] = 'Weekend Days';
$translations['ar']['holidays'] = 'العطلات الرسمية';
$translations['en']['holidays'] = 'Official Holidays';
$translations['ar']['add_holiday'] = 'إضافة عطلة رسمية';
$translations['en']['add_holiday'] = 'Add Official Holiday';
$translations['ar']['holiday_name'] = 'اسم العطلة';
$translations['en']['holiday_name'] = 'Holiday Name';
$translations['ar']['holiday_name_ar_example'] = 'مثال: اليوم الوطني';
$translations['en']['holiday_name_ar_example'] = 'e.g. National Day';
$translations['ar']['leave_reports'] = 'تقارير وتحليلات الإجازات';
$translations['en']['leave_reports'] = 'Leave Reports & Analytics';

// Auth pages translations
$translations['ar']['forgot_password'] = 'نسيت كلمة المرور؟';
$translations['en']['forgot_password'] = 'Forgot Password?';
$translations['ar']['remember_password'] = 'تذكرت كلمة المرور؟';
$translations['en']['remember_password'] = 'Remember your password?';
$translations['ar']['new_password'] = 'كلمة المرور الجديدة';
$translations['en']['new_password'] = 'New Password';
$translations['ar']['confirm_password'] = 'تأكيد كلمة المرور';
$translations['en']['confirm_password'] = 'Confirm Password';
$translations['ar']['reset_password'] = 'إعادة تعيين كلمة المرور';
$translations['en']['reset_password'] = 'Reset Password';
$translations['ar']['email_settings'] = 'إعدادات البريد الإلكتروني';
$translations['en']['email_settings'] = 'Email Settings';
$translations['ar']['email_notifications'] = 'إشعارات البريد الإلكتروني';
$translations['en']['email_notifications'] = 'Email Notifications';
$translations['ar']['email_on'] = 'ON';
$translations['en']['email_on'] = 'ON';
$translations['ar']['email_off'] = 'OFF';
$translations['en']['email_off'] = 'OFF';
$translations['ar']['confirm_disable_email'] = 'هل تريد تعطيل البريد الإلكتروني لجهة العمل هذه؟';
$translations['en']['confirm_disable_email'] = 'Disable email for this organization?';
$translations['ar']['confirm_enable_email'] = 'هل تريد تفعيل البريد الإلكتروني لجهة العمل هذه؟';
$translations['en']['confirm_enable_email'] = 'Enable email for this organization?';
$translations['ar']['test_email_label'] = 'اختبار إعدادات البريد';
$translations['en']['test_email_label'] = 'Test Email Configuration';
$translations['ar']['test_email_placeholder'] = 'أدخل البريد الإلكتروني المستلم';
$translations['en']['test_email_placeholder'] = 'Enter recipient email';
$translations['ar']['send_test'] = 'إرسال اختبار';
$translations['en']['send_test'] = 'Send Test';
$translations['ar']['test_email_desc'] = 'سيتم إرسال رسالة اختبارية باستخدام الإعدادات الحالية. احفظ الإعدادات أولاً قبل الاختبار.';
$translations['en']['test_email_desc'] = 'Sends a test message using the current saved settings. Save settings first before testing.';
$translations['ar']['require_email_verification'] = 'إلزام التحقق من البريد الإلكتروني';
$translations['en']['require_email_verification'] = 'Require Email Verification';
$translations['ar']['email_verification'] = 'التحقق من البريد الإلكتروني';
$translations['en']['email_verification'] = 'Email Verification';
$translations['ar']['email_verified_success'] = 'تم التحقق من بريدك الإلكتروني بنجاح! يمكنك الآن تسجيل الدخول.';
$translations['en']['email_verified_success'] = 'Your email has been verified successfully! You can now log in.';
$translations['ar']['send_verification'] = 'إرسال بريد التحقق';
$translations['en']['send_verification'] = 'Send Verification Email';
$translations['ar']['search'] = 'بحث';
$translations['en']['search'] = 'Search';

// Super Admin Dashboard translations
$translations['ar']['super_admin_title'] = 'لوحة تحكم المدير العام';
$translations['en']['super_admin_title'] = 'Super Admin Control Panel';
$translations['ar']['complete_system_admin_desc'] = 'إدارة كاملة للنظام والتحكم بجميع جهات العمل';
$translations['en']['complete_system_admin_desc'] = 'Complete system administration and control over all organizations';
$translations['ar']['super_admin_warning'] = 'هذه اللوحة خاصة بالمدير العام فقط. جميع الإجراءات مسجلة ومراقبة.';
$translations['en']['super_admin_warning'] = 'This panel is for Super Administrators only. All actions are logged and monitored.';
$translations['ar']['select_organization'] = 'اختر جهة العمل';
$translations['en']['select_organization'] = 'Select Organization';
$translations['ar']['select_org_first'] = 'يرجى اختيار جهة عمل من القائمة أولاً للوصول إلى إعداداتها وبياناتها.';
$translations['en']['select_org_first'] = 'Please select an organization from the list first to access its settings and data.';
$translations['ar']['csrf_token_invalid'] = 'رمز الحماية غير صالح. يرجى إعادة تحميل الصفحة.';
$translations['en']['csrf_token_invalid'] = 'Invalid security token. Please reload the page.';
$translations['ar']['view_system_wide'] = '-- عرض بيانات النظام (جميع جهات العمل) --';
$translations['en']['view_system_wide'] = '-- View System-Wide Data (All Organizations) --';
$translations['ar']['load_data'] = 'تحميل البيانات';
$translations['en']['load_data'] = 'Load Data';
$translations['ar']['active_organizations'] = 'جهات العمل النشطة';
$translations['en']['active_organizations'] = 'Active Organizations';
$translations['ar']['total_users_count'] = 'إجمالي المستخدمين';
$translations['en']['total_users_count'] = 'Total Users';
$translations['ar']['approved_employees_count'] = 'الموظفون المعتمدون';
$translations['en']['approved_employees_count'] = 'Approved Employees';
$translations['ar']['accounts_at_risk'] = 'حسابات معرضة للخطر';
$translations['en']['accounts_at_risk'] = 'Accounts At Risk';
$translations['ar']['orgs_management_section'] = 'إدارة جهات العمل';
$translations['en']['orgs_management_section'] = 'Organizations Management';
$translations['ar']['manage_orgs_btn'] = 'إدارة جميع جهات العمل';
$translations['en']['manage_orgs_btn'] = 'Manage All Organizations';
$translations['ar']['create_edit_delete_orgs'] = 'إنشاء، تعديل، حذف جهات العمل';
$translations['en']['create_edit_delete_orgs'] = 'Create, edit, delete organizations';
$translations['ar']['privacy_codes_btn'] = 'الخصوصية والأكواد';
$translations['en']['privacy_codes_btn'] = 'Privacy & Codes';
$translations['ar']['control_visibility_codes'] = 'التحكم في الرؤية وأكواد الدعوة';
$translations['en']['control_visibility_codes'] = 'Control visibility and invitation codes';
$translations['ar']['registration_user_onboarding'] = 'التسجيل وإدارة المستخدمين الجدد';
$translations['en']['registration_user_onboarding'] = 'Registration & User Onboarding';
$translations['ar']['registration_settings_btn'] = 'إعدادات التسجيل';
$translations['en']['registration_settings_btn'] = 'Registration Settings';
$translations['ar']['reg_control_desc'] = 'التحكم في التسجيل والتحقق من البريد الإلكتروني والموافقات المعلقة';
$translations['en']['reg_control_desc'] = 'Control registration, email verification, pending approvals';
$translations['ar']['reg_activity_log_btn'] = 'سجل نشاط التسجيل';
$translations['en']['reg_activity_log_btn'] = 'Registration Activity Log';
$translations['ar']['reg_activity_desc'] = 'عرض جميع محاولات التسجيل والموافقات';
$translations['en']['reg_activity_desc'] = 'View all registration attempts and approvals';
$translations['ar']['users_roles_section'] = 'إدارة المستخدمين والصلاحيات';
$translations['en']['users_roles_section'] = 'Users & Roles Management';
$translations['ar']['all_users_btn'] = 'جميع المستخدمين';
$translations['en']['all_users_btn'] = 'All Users';
$translations['ar']['users_desc'] = 'إنشاء، تعديل، حذف المستخدمين';
$translations['en']['users_desc'] = 'Create, edit, delete users';
$translations['ar']['assign_roles_btn'] = 'تعيين الصلاحيات';
$translations['en']['assign_roles_btn'] = 'Assign Roles';
$translations['ar']['roles_desc'] = 'التحكم في صلاحيات المستخدمين';
$translations['en']['roles_desc'] = 'Control user permissions';
$translations['ar']['reset_passwords_btn'] = 'إعادة تعيين كلمات المرور';
$translations['en']['reset_passwords_btn'] = 'Reset Passwords';
$translations['ar']['reset_passwords_desc'] = 'إعادة تعيين قسرية لكلمات المرور';
$translations['en']['reset_passwords_desc'] = 'Force password resets';
$translations['ar']['email_notifications_section'] = 'البريد الإلكتروني والإشعارات';
$translations['en']['email_notifications_section'] = 'Email & Notifications';
$translations['ar']['email_settings_btn'] = 'إعدادات البريد';
$translations['en']['email_settings_btn'] = 'Email Settings';
$translations['ar']['email_settings_desc'] = 'إعداد API الإرسال';
$translations['en']['email_settings_desc'] = 'Configure sndr.sh API';
$translations['ar']['email_templates_btn'] = 'قوالب البريد';
$translations['en']['email_templates_btn'] = 'Email Templates';
$translations['ar']['email_templates_desc'] = 'تخصيص رسائل البريد';
$translations['en']['email_templates_desc'] = 'Customize email messages';
$translations['ar']['email_logs_btn'] = 'سجل البريد';
$translations['en']['email_logs_btn'] = 'Email Logs';
$translations['ar']['email_logs_desc'] = 'عرض رسائل البريد المرسلة';
$translations['en']['email_logs_desc'] = 'View sent emails';
$translations['ar']['security_monitoring_section'] = 'الأمان والمراقبة';
$translations['en']['security_monitoring_section'] = 'Security & Monitoring';
$translations['ar']['failed_login_attempts'] = 'محاولات تسجيل دخول فاشلة (آخر 24 ساعة)';
$translations['en']['failed_login_attempts'] = 'Failed Login Attempts (Last 24h)';
$translations['ar']['username_label'] = 'اسم المستخدم';
$translations['en']['username_label'] = 'Username';
$translations['ar']['attempts_label'] = 'المحاولات';
$translations['en']['attempts_label'] = 'Attempts';
$translations['ar']['last_try_label'] = 'آخر محاولة';
$translations['en']['last_try_label'] = 'Last Try';
$translations['ar']['no_failed_attempts'] = 'لا توجد محاولات فاشلة';
$translations['en']['no_failed_attempts'] = 'No failed attempts';
$translations['ar']['code_attempt_breaches'] = 'محاولات اختراق الأكواد (آخر 24 ساعة)';
$translations['en']['code_attempt_breaches'] = 'Code Attempt Breaches (Last 24h)';
$translations['ar']['no_code_attempts'] = 'لا توجد محاولات أكواد فاشلة';
$translations['en']['no_code_attempts'] = 'No failed code attempts';
$translations['ar']['view_activity_log_btn'] = 'عرض سجل النشاطات الكامل';
$translations['en']['view_activity_log_btn'] = 'View Complete Activity Log';
$translations['ar']['system_settings_config'] = 'إعدادات النظام والتكوين';
$translations['en']['system_settings_config'] = 'System Settings & Configuration';
$translations['ar']['system_settings_title'] = 'إعدادات النظام';
$translations['en']['system_settings_title'] = 'System Settings';
$translations['ar']['system_settings_desc'] = 'إدارة الإعدادات العامة للنظام (خاص بالمشرف العام)';
$translations['en']['system_settings_desc'] = 'Manage system-wide settings (Super Admin only)';
$translations['ar']['maintenance_mode'] = 'وضع الصيانة';
$translations['en']['maintenance_mode'] = 'Maintenance Mode';
$translations['ar']['maintenance_mode_desc'] = 'إخفاء النظام عن المستخدمين العاديين مع إبقاء دخول المشرف العام متاحاً';
$translations['en']['maintenance_mode_desc'] = 'Hide the system from regular users; super_admin login remains accessible';
$translations['ar']['maintenance_mode_msg'] = 'النظام قيد الصيانة حالياً. يُرجى المحاولة لاحقاً.';
$translations['en']['maintenance_mode_msg'] = 'The system is currently under maintenance. Please try again later.';
$translations['ar']['allow_new_org_registration'] = 'السماح بتسجيل مؤسسات جديدة';
$translations['en']['allow_new_org_registration'] = 'Allow New Organization Registration';
$translations['ar']['allow_new_org_registration_desc'] = 'السماح للمستخدمين بإنشاء حسابات مؤسسات جديدة من صفحة التسجيل';
$translations['en']['allow_new_org_registration_desc'] = 'Allow users to create new organization accounts from the registration page';
$translations['ar']['auto_approve_orgs'] = 'موافقة تلقائية على المؤسسات';
$translations['en']['auto_approve_orgs'] = 'Auto-Approve Organizations';
$translations['ar']['auto_approve_orgs_desc'] = 'عند التعطيل، تتطلب المؤسسات الجديدة موافقة يدوية من المشرف العام';
$translations['en']['auto_approve_orgs_desc'] = 'When disabled, new organizations require manual approval by Super Admin';
$translations['ar']['min_password_length'] = 'الحد الأدنى لطول كلمة المرور';
$translations['en']['min_password_length'] = 'Minimum Password Length';
$translations['ar']['min_password_length_desc'] = 'الحد الأدنى لعدد الأحرف المطلوبة لكلمة المرور';
$translations['en']['min_password_length_desc'] = 'Minimum number of characters required for passwords';
$translations['ar']['max_login_attempts'] = 'الحد الأقصى لمحاولات الدخول';
$translations['en']['max_login_attempts'] = 'Max Login Attempts';
$translations['ar']['max_login_attempts_desc'] = 'قفل الحساب مؤقتاً بعد هذا العدد من المحاولات الفاشلة';
$translations['en']['max_login_attempts_desc'] = 'Temporarily lock the account after this many failed attempts';
$translations['ar']['session_lifetime'] = 'مدة الجلسة';
$translations['en']['session_lifetime'] = 'Session Lifetime';
$translations['ar']['session_lifetime_desc'] = 'مدة بقاء الجلسة نشطة قبل طلب إعادة تسجيل الدخول';
$translations['en']['session_lifetime_desc'] = 'How long a session stays active before requiring re-login';
$translations['ar']['localization'] = 'التوطين واللغة';
$translations['en']['localization'] = 'Localization';
$translations['ar']['company_name_ar'] = 'اسم الشركة (عربي)';
$translations['en']['company_name_ar'] = 'Company Name (Arabic)';
$translations['ar']['company_name_en'] = 'اسم الشركة (إنجليزي)';
$translations['en']['company_name_en'] = 'Company Name (English)';
$translations['ar']['company_name_ar_default'] = 'نظام إدارة الموارد البشرية';
$translations['en']['company_name_ar_default'] = 'نظام إدارة الموارد البشرية';
$translations['ar']['default_language'] = 'اللغة الافتراضية';
$translations['en']['default_language'] = 'Default Language';
$translations['ar']['arabic'] = 'العربية';
$translations['en']['arabic'] = 'Arabic';
$translations['ar']['english'] = 'English';
$translations['en']['english'] = 'English';
$translations['ar']['contact_email'] = 'البريد الإلكتروني للتواصل';
$translations['en']['contact_email'] = 'Contact Email';
$translations['ar']['contact_email_desc'] = 'بريد التواصل العام للنظام (يظهر في صفحة التسجيل وصفحات الخطأ)';
$translations['en']['contact_email_desc'] = 'System contact email (shown on registration page and error pages)';
$translations['ar']['max_organizations'] = 'الحد الأقصى للمؤسسات';
$translations['en']['max_organizations'] = 'Maximum Organizations';
$translations['ar']['max_organizations_desc'] = 'الحد الأقصى لعدد المؤسسات المسموح بها في النظام';
$translations['en']['max_organizations_desc'] = 'Maximum number of organizations allowed in the system';
$translations['ar']['minutes'] = 'دقيقة';
$translations['en']['minutes'] = 'minutes';
$translations['ar']['system_config_tips'] = 'نصائح تكوين النظام';
$translations['en']['system_config_tips'] = 'System Configuration Tips';
$translations['ar']['config_tip1'] = 'تكوين إعدادات البريد لكل جهة عمل في <strong>لوحة الإعدادات</strong>';
$translations['en']['config_tip1'] = 'Configure email settings per organization in <strong>Settings panel</strong>';
$translations['ar']['config_tip2'] = 'التحكم في رؤية جهات العمل والأكواد في <strong>الخصوصية والأكواد</strong>';
$translations['en']['config_tip2'] = 'Control organization visibility and codes in <strong>Privacy & Codes</strong>';
$translations['ar']['config_tip3'] = 'مراقبة سجل النشاطات لمسار التدقيق';
$translations['en']['config_tip3'] = 'Monitor activity logs for audit trail';
$translations['ar']['config_tip4'] = '<strong>تحديد المعدل:</strong> 5 محاولات دخول فاشلة = قفل 15 دقيقة | 5 محاولات كود = قفل ساعة';
$translations['en']['config_tip4'] = '<strong>Rate Limiting:</strong> 5 failed logins = 15-min lockout | 5 code attempts = 1-hour lockout';
$translations['ar']['config_tip5'] = 'يمكن تفعيل التحقق من البريد الإلكتروني لكل جهة عمل';
$translations['en']['config_tip5'] = 'Email verification can be toggled per organization';
$translations['ar']['config_tip6'] = 'يمكن إعادة إنشاء أكواد الدعوة (12 حرف) في أي وقت';
$translations['en']['config_tip6'] = 'Organization invitation codes (12-char alphanumeric) can be regenerated anytime';
$translations['ar']['quick_actions'] = 'إجراءات سريعة';
$translations['en']['quick_actions'] = 'Quick Actions';
$translations['ar']['clear_login_lockouts'] = 'مسح أقفال الدخول';
$translations['en']['clear_login_lockouts'] = 'Clear Login Lockouts';
$translations['ar']['regenerate_codes_btn'] = 'إعادة إنشاء الأكواد';
$translations['en']['regenerate_codes_btn'] = 'Regenerate Codes';
$translations['ar']['export_data_btn'] = 'تصدير البيانات';
$translations['en']['export_data_btn'] = 'Export Data';
$translations['ar']['system_diagnostics_btn'] = 'تشخيص النظام';
$translations['en']['system_diagnostics_btn'] = 'System Diagnostics';
$translations['ar']['public'] = 'عام';
$translations['en']['public'] = 'Public';
$translations['ar']['private'] = 'خاص';
$translations['en']['private'] = 'Private';
$translations['ar']['enter_org'] = 'دخول للجهة';
$translations['en']['enter_org'] = 'Enter Organization';
$translations['ar']['system_core'] = 'نواة النظام';
$translations['en']['system_core'] = 'System Core';
$translations['ar']['pending_requests'] = 'طلبات الإضافة المعلقة';
$translations['en']['pending_requests'] = 'Pending Addition Requests';
$translations['ar']['no_pending_requests'] = 'لا توجد طلبات إضافة معلقة حالياً.';
$translations['en']['no_pending_requests'] = 'No pending addition requests.';
$translations['ar']['org_name'] = 'جهة العمل';
$translations['en']['org_name'] = 'Organization';
$translations['ar']['contact_info'] = 'بيانات المسؤول والتواصل';
$translations['en']['contact_info'] = 'Manager & Contact Info';
$translations['ar']['request_date'] = 'تاريخ الطلب';
$translations['en']['request_date'] = 'Request Date';
$translations['ar']['no_notes'] = 'لا توجد ملاحظات';
$translations['en']['no_notes'] = 'No notes';
$translations['ar']['approve_activate'] = 'قبول وتفعيل';
$translations['en']['approve_activate'] = 'Approve & Activate';
$translations['ar']['reject_request'] = 'رفض';
$translations['en']['reject_request'] = 'Reject';
$translations['ar']['confirm_approve_org'] = 'هل أنت متأكد من قبول وتفعيل هذه الجهة وإنشاء حساب المسؤول وتوليد كلمة مرور مؤقتة؟';
$translations['en']['confirm_approve_org'] = 'Are you sure you want to approve this organization and create the manager account with a temporary password?';
$translations['ar']['confirm_reject_request'] = 'هل أنت متأكد من رفض هذا الطلب؟';
$translations['en']['confirm_reject_request'] = 'Are you sure you want to reject this request?';
$translations['ar']['org_approved_success'] = 'تم قبول جهة العمل وتفعيلها بنجاح!';
$translations['en']['org_approved_success'] = 'Organization approved and activated successfully!';
$translations['ar']['manager_account_info'] = 'بيانات حساب المسؤول';
$translations['en']['manager_account_info'] = 'Manager Account Info';
$translations['ar']['temp_password_label'] = 'كلمة المرور المؤقتة';
$translations['en']['temp_password_label'] = 'Temporary Password';
$translations['ar']['save_credentials'] = 'يرجى نسخ وحفظ هذه البيانات وإرسالها للمسؤول فوراً.';
$translations['en']['save_credentials'] = 'Please copy and save this data and send it to the manager immediately.';
$translations['ar']['request_not_found'] = 'الطلب غير موجود أو تمت معالجته بالفعل.';
$translations['en']['request_not_found'] = 'Request not found or already processed.';
$translations['ar']['rejected_success'] = 'تم رفض طلب إضافة جهة العمل بنجاح.';
$translations['en']['rejected_success'] = 'Organization addition request rejected successfully.';
$translations['ar']['cannot_suspend_default'] = 'لا يمكن تعطيل جهة العمل الافتراضية للنظام.';
$translations['en']['cannot_suspend_default'] = 'Cannot suspend the default system organization.';

// Organization Codes translations
$translations['ar']['org_codes_mgmt'] = 'إدارة أكواد التحاق المؤسسات';
$translations['en']['org_codes_mgmt'] = 'Organization Codes Management';
$translations['ar']['org_codes_desc'] = 'التحكم في رؤية المؤسسات والأكواد الخاصة للموظفين الجدد';
$translations['en']['org_codes_desc'] = 'Control organization visibility and invitation codes for new employees';
$translations['ar']['org_list'] = 'قائمة المؤسسات';
$translations['en']['org_list'] = 'Organizations List';
$translations['ar']['status_label'] = 'الحالة';
$translations['en']['status_label'] = 'Status';
$translations['ar']['invitation_code'] = 'رمز الالتحاق';
$translations['en']['invitation_code'] = 'Invitation Code';
$translations['ar']['last_code_update'] = 'آخر تحديث للرمز';
$translations['en']['last_code_update'] = 'Last Code Update';
$translations['ar']['not_updated'] = 'لم يتم تحديث';
$translations['en']['not_updated'] = 'Not updated';
$translations['ar']['copy_code'] = 'نسخ';
$translations['en']['copy_code'] = 'Copy';
$translations['ar']['make_private'] = 'خاص';
$translations['en']['make_private'] = 'Private';
$translations['ar']['make_public'] = 'عام';
$translations['en']['make_public'] = 'Public';
$translations['ar']['new_code'] = 'رمز جديد';
$translations['en']['new_code'] = 'New Code';
$translations['ar']['confirm_make_private'] = 'هل تريد تحويل هذه المؤسسة إلى خاصة؟';
$translations['en']['confirm_make_private'] = 'Are you sure you want to make this organization private?';
$translations['ar']['confirm_make_public'] = 'هل تريد تحويل هذه المؤسسة إلى عامة؟';
$translations['en']['confirm_make_public'] = 'Are you sure you want to make this organization public?';
$translations['ar']['confirm_new_code'] = 'إنشاء كود جديد سيلغي الكود القديم. هل تريد المتابعة؟';
$translations['en']['confirm_new_code'] = 'Creating a new code will invalidate the old one. Continue?';
$translations['ar']['visibility_updated'] = 'تم تحديث حالة رؤية المؤسسة بنجاح.';
$translations['en']['visibility_updated'] = 'Organization visibility updated successfully.';
$translations['ar']['org_not_found'] = 'المؤسسة غير موجودة.';
$translations['en']['org_not_found'] = 'Organization not found.';
$translations['ar']['code_updated'] = 'تم إنشاء كود جديد بنجاح';
$translations['en']['code_updated'] = 'New code generated successfully';
$translations['ar']['previous_code'] = 'الكود السابق';
$translations['en']['previous_code'] = 'Previous code';
$translations['ar']['public_orgs_desc'] = 'يمكن للموظفين الجدد رؤية هذه المؤسسات مباشرة في قائمة الاختيار عند التسجيل.';
$translations['en']['public_orgs_desc'] = 'New employees can see these organizations directly in the selection list during registration.';
$translations['ar']['public_orgs_features'] = 'لا يتطلب كود التحاق - مرئي للجميع - الخيار الافتراضي';
$translations['en']['public_orgs_features'] = 'No code required - Visible to all - Default option';
$translations['ar']['no_code_required'] = 'لا يتطلب كود التحاق';
$translations['en']['no_code_required'] = 'No invitation code required';
$translations['ar']['visible_to_all'] = 'مرئي للجميع';
$translations['en']['visible_to_all'] = 'Visible to all';
$translations['ar']['default_option'] = 'الخيار الافتراضي';
$translations['en']['default_option'] = 'Default option';
$translations['ar']['requires_code'] = 'يتطلب كود التحاق صحيح';
$translations['en']['requires_code'] = 'Requires valid invitation code';
$translations['ar']['not_visible_in_list'] = 'غير مرئي في القائمة';
$translations['en']['not_visible_in_list'] = 'Not visible in the list';
$translations['ar']['more_secure'] = 'أكثر أماناً';
$translations['en']['more_secure'] = 'More secure';
$translations['ar']['private_orgs_desc'] = 'لا تظهر في قائمة الاختيار. يجب على الموظفين إدخال كود التحاق خاص للانضمام.';
$translations['en']['private_orgs_desc'] = 'Not shown in the selection list. Employees must enter a private invitation code to join.';
$translations['ar']['usage_steps'] = 'خطوات الاستخدام';
$translations['en']['usage_steps'] = 'Usage Steps';
$translations['ar']['step1_title'] = 'اختر وضع المؤسسة';
$translations['en']['step1_title'] = 'Choose Organization Mode';
$translations['ar']['step1_desc'] = 'اضغط على "عام" أو "خاص" لتحديد كيفية رؤية الموظفين الجدد للمؤسسة.';
$translations['en']['step1_desc'] = 'Click "Public" or "Private" to set how new employees see the organization.';
$translations['ar']['step2_title'] = 'شارك الكود';
$translations['en']['step2_title'] = 'Share the Code';
$translations['ar']['step2_desc'] = 'للمؤسسات الخاصة، شارك الكود الفريد مع الموظفين الجدد الذين يريدون الانضمام.';
$translations['en']['step2_desc'] = 'For private organizations, share the unique code with new employees who want to join.';
$translations['ar']['step3_title'] = 'حدث الكود عند الحاجة';
$translations['en']['step3_title'] = 'Update Code When Needed';
$translations['ar']['step3_desc'] = 'اضغط "رمز جديد" لإنشاء كود مختلف وإلغاء الكود القديم.';
$translations['en']['step3_desc'] = 'Click "New Code" to generate a different code and invalidate the old one.';
$translations['ar']['code_copied'] = 'تم نسخ الكود';
$translations['en']['code_copied'] = 'Code copied';

// Registration Control translations
$translations['ar']['reg_control_title'] = 'لوحة التحكم - إدارة التسجيل';
$translations['en']['reg_control_title'] = 'Registration Control Panel';
$translations['ar']['reg_control_desc_text'] = 'تحكم في التسجيلات والتحقق من البريد الإلكتروني وإعدادات المؤسسات';
$translations['en']['reg_control_desc_text'] = 'Control who can register, email verification, and organization settings';
$translations['ar']['total_users_stat'] = 'إجمالي المستخدمين';
$translations['en']['total_users_stat'] = 'Total Users';
$translations['ar']['verified_users'] = 'مستخدمون مُتحققون';
$translations['en']['verified_users'] = 'Verified Users';
$translations['ar']['pending_verification'] = 'في انتظار التحقق';
$translations['en']['pending_verification'] = 'Pending Verification';
$translations['ar']['organizations_stat'] = 'المؤسسات';
$translations['en']['organizations_stat'] = 'Organizations';
$translations['ar']['global_reg_settings'] = 'إعدادات التسجيل العامة';
$translations['en']['global_reg_settings'] = 'Global Registration Settings';
$translations['ar']['allow_public_reg'] = 'السماح بالتسجيل العام';
$translations['en']['allow_public_reg'] = 'Allow Public Registration';
$translations['ar']['reg_disabled_desc'] = 'عند التعطيل، سيتمكن المستخدمون المدعوون فقط من التسجيل';
$translations['en']['reg_disabled_desc'] = 'When disabled, only invited users can register';
$translations['ar']['require_email_verif'] = 'إلزام التحقق من البريد الإلكتروني';
$translations['en']['require_email_verif'] = 'Require Email Verification';
$translations['ar']['email_verif_desc'] = 'يجب على المستخدمين التحقق من بريدهم الإلكتروني بعد التسجيل';
$translations['en']['email_verif_desc'] = 'Users must verify their email address after registration';
$translations['ar']['org_reg_settings'] = 'إعدادات تسجيل المؤسسات';
$translations['en']['org_reg_settings'] = 'Organization Registration Settings';
$translations['ar']['users_count'] = 'مستخدمين';
$translations['en']['users_count'] = 'users';
$translations['ar']['code_required'] = 'يتطلب كود';
$translations['en']['code_required'] = 'Code Required';
$translations['ar']['edit_settings'] = 'تعديل';
$translations['en']['edit_settings'] = 'Edit';
$translations['ar']['edit_org_settings'] = 'تعديل إعدادات المؤسسة';
$translations['en']['edit_org_settings'] = 'Edit Organization Settings';
$translations['ar']['show_in_public_list'] = 'إظهار في القائمة العامة';
$translations['en']['show_in_public_list'] = 'Show in Public List';
$translations['ar']['require_inv_code'] = 'يتطلب كود التحاق';
$translations['en']['require_inv_code'] = 'Require Invitation Code';
$translations['ar']['save_changes'] = 'حفظ التغييرات';
$translations['en']['save_changes'] = 'Save Changes';
$translations['ar']['pending_verifications_title'] = 'التسجيلات في انتظار التحقق';
$translations['en']['pending_verifications_title'] = 'Pending Verifications';
$translations['ar']['no_pending_verifications'] = 'لا توجد تسجيلات في انتظار التحقق';
$translations['en']['no_pending_verifications'] = 'No pending verifications';
$translations['ar']['approve_reg'] = 'الموافقة';
$translations['en']['approve_reg'] = 'Approve';
$translations['ar']['reject_reg'] = 'الرفض';
$translations['en']['reject_reg'] = 'Reject';
$translations['ar']['confirm_delete_reg'] = 'حذف هذا التسجيل؟';
$translations['en']['confirm_delete_reg'] = 'Delete this registration?';
$translations['ar']['how_to_control_reg'] = 'كيفية التحكم في التسجيل';
$translations['en']['how_to_control_reg'] = 'How to Control Registration';
$translations['ar']['available_controls'] = 'الخيارات المتاحة:';
$translations['en']['available_controls'] = 'Available Controls:';
$translations['ar']['global_settings_label'] = 'الإعدادات العامة:';
$translations['en']['global_settings_label'] = 'Global Settings:';
$translations['ar']['global_settings_desc'] = 'تفعيل/تعطيل جميع التسجيلات وإلزام التحقق من البريد الإلكتروني';
$translations['en']['global_settings_desc'] = 'Enable/disable all registrations and require email verification';
$translations['ar']['per_org_label'] = 'لكل مؤسسة:';
$translations['en']['per_org_label'] = 'Per-Organization:';
$translations['ar']['per_org_desc'] = 'اجعل المؤسسات عامة أو خاصة أو تتطلب أكوادًا من الدعوات';
$translations['en']['per_org_desc'] = 'Make organizations public, private, or require invitation codes';
$translations['ar']['pending_approvals_label'] = 'الموافقات المعلقة:';
$translations['en']['pending_approvals_label'] = 'Pending Approvals:';
$translations['ar']['pending_approvals_desc'] = 'الموافقة على تسجيلات المستخدمين أو رفضها';
$translations['en']['pending_approvals_desc'] = 'Approve or reject user registrations that need verification';
$translations['ar']['reg_enabled_msg'] = 'تم تفعيل التسجيل';
$translations['en']['reg_enabled_msg'] = 'Registration enabled';
$translations['ar']['reg_disabled_msg'] = 'تم تعطيل التسجيل';
$translations['en']['reg_disabled_msg'] = 'Registration disabled';
$translations['ar']['email_verif_required_msg'] = 'تم إلزام التحقق من البريد الإلكتروني';
$translations['en']['email_verif_required_msg'] = 'Email verification required';
$translations['ar']['email_verif_not_required_msg'] = 'تم إلغاء إلزام التحقق من البريد الإلكتروني';
$translations['en']['email_verif_not_required_msg'] = 'Email verification not required';
$translations['ar']['org_settings_updated'] = 'تم تحديث إعدادات المؤسسة';
$translations['en']['org_settings_updated'] = 'Organization settings updated';
$translations['ar']['reg_approved_msg'] = 'تم الموافقة على التسجيل';
$translations['en']['reg_approved_msg'] = 'Registration approved';
$translations['ar']['reg_rejected_msg'] = 'تم رفض التسجيل';
$translations['en']['reg_rejected_msg'] = 'Registration rejected';
$translations['ar']['email_blocked_msg'] = 'تم حظر البريد الإلكتروني من التسجيل';
$translations['en']['email_blocked_msg'] = 'Email blocked from registration';
$translations['ar']['email_unblocked_msg'] = 'تم إلغاء حظر البريد الإلكتروني';
$translations['en']['email_unblocked_msg'] = 'Email unblocked';

// Settings page translations
$translations['ar']['form_fields_customization'] = 'تخصيص حقول النماذج (التحكم بالخيارات الظاهرة والمطلوبة)';
$translations['en']['form_fields_customization'] = 'Form Fields Customization (Toggle visibility and requirements)';
$translations['ar']['form_fields_desc'] = 'يمكنك تفعيل أو تعطيل ظهور الحقول في فورم التسجيل وفورم طلب الإجازة، وتحديد ما إذا كانت مطلوبة إجبارياً أم اختيارية.';
$translations['en']['form_fields_desc'] = 'Enable or disable field visibility in registration and leave request forms, and set whether they are required or optional.';
$translations['ar']['reg_form_fields'] = 'حقول فورم طلب التسجيل الجديد';
$translations['en']['reg_form_fields'] = 'New Registration Form Fields';
$translations['ar']['leave_form_fields'] = 'حقول فورم طلب الإجازة للموظف';
$translations['en']['leave_form_fields'] = 'Leave Request Form Fields';
$translations['ar']['visible_in_form'] = 'ظاهر في الفورم';
$translations['en']['visible_in_form'] = 'Visible in form';
$translations['ar']['required_field'] = 'مطلوب إجباري *';
$translations['en']['required_field'] = 'Required *';
$translations['ar']['phone_field'] = 'رقم الجوال (Phone)';
$translations['en']['phone_field'] = 'Phone Number';
$translations['ar']['dept_field'] = 'القسم (Department)';
$translations['en']['dept_field'] = 'Department';
$translations['ar']['job_field'] = 'المسمى الوظيفي (Job Title)';
$translations['en']['job_field'] = 'Job Title';
$translations['ar']['balance_field'] = 'الأرصدة الافتتاحية للإجازات';
$translations['en']['balance_field'] = 'Opening Leave Balances';
$translations['ar']['reason_field'] = 'سبب الإجازة (Reason)';
$translations['en']['reason_field'] = 'Leave Reason';
$translations['ar']['attachment_field'] = 'إثبات نظام الوزارة (Attachment)';
$translations['en']['attachment_field'] = 'Ministry System Proof (Attachment)';
$translations['ar']['weekend_friday_saturday'] = 'الجمعة والسبت (الافتراضي)';
$translations['en']['weekend_friday_saturday'] = 'Friday & Saturday (Default)';
$translations['ar']['weekend_friday'] = 'الجمعة فقط';
$translations['en']['weekend_friday'] = 'Friday Only';
$translations['ar']['weekend_saturday_sunday'] = 'السبت والأحد';
$translations['en']['weekend_saturday_sunday'] = 'Saturday & Sunday';
$translations['ar']['weekend_sunday'] = 'الأحد فقط';
$translations['en']['weekend_sunday'] = 'Sunday Only';
$translations['ar']['weekend_none'] = 'لا توجد عطلات نهاية أسبوع';
$translations['en']['weekend_none'] = 'No Weekends';
$translations['ar']['weekend_desc'] = 'سيتم استبعاد هذه الأيام تلقائياً عند حساب الخصم من رصيد إجازات الموظفين.';
$translations['en']['weekend_desc'] = 'These days will be automatically excluded when calculating leave balance deductions.';
$translations['ar']['sndr_api_key'] = 'Sndr.sh API Key';
$translations['en']['sndr_api_key'] = 'Sndr.sh API Key';
$translations['ar']['sndr_api_desc'] = 'حافظ على سرية هذا المفتاح. يمكنك أيضاً تعيينه عبر متغيرات البيئة.';
$translations['en']['sndr_api_desc'] = 'Keep this secret. You can also set it via environment variables.';
$translations['ar']['sender_email'] = 'البريد الإلكتروني للمرسل';
$translations['en']['sender_email'] = 'Sender Email';
$translations['ar']['sender_name'] = 'اسم المرسل';
$translations['en']['sender_name'] = 'Sender Name';
$translations['ar']['site_name_ar_setting'] = 'اسم الموقع (AR)';
$translations['en']['site_name_ar_setting'] = 'Site Name (AR)';
$translations['ar']['site_name_en_setting'] = 'اسم الموقع (EN)';
$translations['en']['site_name_en_setting'] = 'Site Name (EN)';

// Leaves/Reports translations
$translations['ar']['reports_and_analytics'] = 'تقارير وتحليلات الإجازات';
$translations['en']['reports_and_analytics'] = 'Leave Reports & Analytics';
$translations['ar']['total_work_days'] = 'إجمالي أيام العمل الفعلية';
$translations['en']['total_work_days'] = 'Total Actual Work Days';
$translations['ar']['approved_requests_count'] = 'الطلبات المعتمدة';
$translations['en']['approved_requests_count'] = 'Approved Requests';
$translations['ar']['pending_requests_count'] = 'الطلبات المعلقة';
$translations['en']['pending_requests_count'] = 'Pending Requests';
$translations['ar']['advanced_filter_search'] = 'تصفية وبحث متقدم';
$translations['en']['advanced_filter_search'] = 'Advanced Filter & Search';
$translations['ar']['employee_name_or_code'] = 'اسم الموظف أو كود الطلب';
$translations['en']['employee_name_or_code'] = 'Employee Name or Request Code';
$translations['ar']['search_dots'] = 'البحث...';
$translations['en']['search_dots'] = 'Search...';
$translations['ar']['from_start_date'] = 'من تاريخ البدء';
$translations['en']['from_start_date'] = 'From Start Date';
$translations['ar']['to_end_date'] = 'إلى تاريخ الانتهاء';
$translations['en']['to_end_date'] = 'To End Date';
$translations['ar']['update_filter_report'] = 'تحديث وتصفية التقرير';
$translations['en']['update_filter_report'] = 'Update & Filter Report';
$translations['ar']['export_current_report'] = 'تصدير التقرير الحالي إلى Excel';
$translations['en']['export_current_report'] = 'Export Current Report to Excel';
$translations['ar']['employee'] = 'الموظف';
$translations['en']['employee'] = 'Employee';
$translations['ar']['request_code'] = 'كود الطلب';
$translations['en']['request_code'] = 'Request Code';
$translations['ar']['date_and_duration'] = 'التاريخ والمدة';
$translations['en']['date_and_duration'] = 'Date & Duration';
$translations['ar']['actual_work_days'] = 'أيام العمل الفعلية';
$translations['en']['actual_work_days'] = 'Actual Work Days';
$translations['ar']['request_status'] = 'حالة الطلب';
$translations['en']['request_status'] = 'Request Status';
$translations['ar']['day'] = 'يوم';
$translations['en']['day'] = 'day';
$translations['ar']['to'] = 'إلى';
$translations['en']['to'] = 'to';
$translations['ar']['from'] = 'من';
$translations['en']['from'] = 'from';
$translations['ar']['view_attachment'] = 'عرض الإثبات';
$translations['en']['view_attachment'] = 'View Attachment';
$translations['ar']['no_attachment'] = 'لا يوجد';
$translations['en']['no_attachment'] = 'None';
$translations['ar']['not_specified'] = '-';
$translations['en']['not_specified'] = '-';

// leave request validation messages
$translations['ar']['reason_required'] = 'سبب الإجازة مطلوب إجبارياً.';
$translations['en']['reason_required'] = 'Leave reason is required.';
$translations['ar']['attachment_required'] = 'إرفاق إثبات نظام الوزارة مطلوب إجبارياً.';
$translations['en']['attachment_required'] = 'Ministry system proof attachment is required.';
$translations['ar']['end_after_start'] = 'End date must be after start date.';
$translations['en']['end_after_start'] = 'End date must be after start date.';
$translations['ar']['upload_attachment'] = 'إرفاق صورة أو PDF من النظام';
$translations['en']['upload_attachment'] = 'Upload image or PDF from system';
$translations['ar']['file_uploaded'] = 'تم إرفاق الملف بنجاح!';
$translations['en']['file_uploaded'] = 'File uploaded successfully!';
$translations['ar']['file_uploaded_btn'] = 'تم إرفاق الملف';
$translations['en']['file_uploaded_btn'] = 'File Uploaded';
$translations['ar']['calendar_days_suffix'] = '(أيام تقويمية)';
$translations['en']['calendar_days_suffix'] = '(Calendar Days)';

// Login page
$translations['ar']['want_new_org'] = 'تريد تسجيل منشأة جديدة؟';
$translations['en']['want_new_org'] = 'Want to register a new organization?';
$translations['ar']['request_org'] = 'تسجيل جهة عملك';
$translations['en']['request_org'] = 'Register Your Organization';
$translations['ar']['request_new_org_title'] = 'طلب إضافة جهة عمل جديدة';
$translations['en']['request_new_org_title'] = 'Request New Organization';
$translations['ar']['request_org_desc'] = 'انضم إلينا كشريك مستأجر جديد وسنقوم بإنشاء بوابتك وجدول الصلاحيات وإعداداتك المخصصة.';
$translations['en']['request_org_desc'] = 'Join us as a new tenant partner and we will create your portal, permissions, and custom settings.';
$translations['ar']['org_info'] = 'بيانات جهة العمل المطلوبة';
$translations['en']['org_info'] = 'Required Organization Info';
$translations['ar']['manager_info'] = 'بيانات المسؤول والمشرف المباشر';
$translations['en']['manager_info'] = 'Manager & Supervisor Info';
$translations['ar']['full_name_placeholder'] = 'مثال: أحمد الحربي';
$translations['en']['full_name_placeholder'] = 'e.g. Ahmed Al-Harbi';
$translations['ar']['email_placeholder'] = 'name@domain.com';
$translations['en']['email_placeholder'] = 'name@domain.com';
$translations['ar']['phone_placeholder'] = '05xxxxxxxx';
$translations['en']['phone_placeholder'] = '05xxxxxxxx';
$translations['ar']['notes_placeholder'] = 'اكتب هنا أي تفاصيل أو حقول ترغب في توفرها بنظامك...';
$translations['en']['notes_placeholder'] = 'Write any details or custom fields you want in your system...';
$translations['ar']['submit_request'] = 'إرسال طلب تسجيل الجهة';
$translations['en']['submit_request'] = 'Submit Organization Request';
$translations['ar']['slug_used'] = 'الرابط المخصص (Slug) محجوز بالفعل لجهة أخرى، يرجى اختيار اسم مختلف.';
$translations['en']['slug_used'] = 'The slug is already reserved for another organization, please choose a different name.';
$translations['ar']['all_fields_required'] = 'جميع الحقول المطلوبة يجب تعبئتها.';
$translations['en']['all_fields_required'] = 'All required fields must be filled.';
$translations['ar']['slug_format_error'] = 'الرابط المخصص (Slug) يجب أن يحتوي على حروف صغيرة، أرقام، وشُرطة فقط وبدون مسافات.';
$translations['en']['slug_format_error'] = 'Slug must contain lowercase letters, numbers, and dashes only (no spaces).';
$translations['ar']['request_submitted'] = 'تم تقديم طلب إضافة جهة العمل بنجاح! سيقوم فريق المراجعة بمراجعته والتواصل معك قريباً لتأكيد التفعيل.';
$translations['en']['request_submitted'] = 'Organization request submitted successfully! The review team will review it and contact you soon.';
$translations['ar']['request_error'] = 'حدث خطأ أثناء حفظ الطلب';
$translations['en']['request_error'] = 'An error occurred while saving the request';
$translations['ar']['slug_tip'] = 'سيتم استخدام هذا الرابط لتحديد جهة العمل للوصول الخاص بموظفيك لاحقاً. حروف صغيرة، أرقام، وشُرطة فقط.';
$translations['en']['slug_tip'] = 'This slug identifies your organization for employees. Lowercase letters, numbers, and dashes only.';
$translations['ar']['follow_up_email'] = 'يمكنك متابعة حالة الطلب عبر بريدك الإلكتروني.';
$translations['en']['follow_up_email'] = 'You can follow up on the request status via your email.';
$translations['ar']['manager_full_name_label'] = 'اسم المسؤول بالكامل';
$translations['en']['manager_full_name_label'] = 'Manager Full Name';
$translations['ar']['manager_email_label'] = 'البريد الإلكتروني للمسؤول';
$translations['en']['manager_email_label'] = 'Manager Email';
$translations['ar']['manager_phone_label'] = 'رقم الجوال للتواصل';
$translations['en']['manager_phone_label'] = 'Contact Phone Number';
$translations['ar']['notes_label'] = 'ملاحظات أو متطلبات خاصة';
$translations['en']['notes_label'] = 'Notes or Special Requirements';

// Register page
$translations['ar']['choose_org'] = 'اختر جهة عملك / المؤسسة *';
$translations['en']['choose_org'] = 'Choose Your Organization *';
$translations['ar']['choose_from_list'] = '-- اختر من القائمة --';
$translations['en']['choose_from_list'] = '-- Choose from list --';
$translations['ar']['org_not_listed'] = 'إذا كانت مؤسستك غير مدرجة هنا، قد تكون خاصة. في هذه الحالة، اطلق كود الالتحاق من إدارتك.';
$translations['en']['org_not_listed'] = 'If your organization is not listed, it may be private. Ask your admin for an invitation code.';
$translations['ar']['have_invite_code'] = 'أو: هل لديك كود التحاق خاص؟';
$translations['en']['have_invite_code'] = 'Or: Do you have an invitation code?';
$translations['ar']['enter_code_placeholder'] = 'أدخل كود التحاق (مثال: ABC123DEF456)';
$translations['en']['enter_code_placeholder'] = 'Enter invitation code (e.g. ABC123DEF456)';
$translations['ar']['verify_code'] = 'تحقق من الكود';
$translations['en']['verify_code'] = 'Verify Code';
$translations['ar']['code_verified'] = 'تم التحقق من الكود';
$translations['en']['code_verified'] = 'Code verified';
$translations['ar']['code_description'] = 'الأكواد الخاصة تسمح للموظفين الجدد بالالتحاق بمؤسسات محددة فقط.';
$translations['en']['code_description'] = 'Private codes allow new employees to join specific organizations only.';
$translations['ar']['no_org_selected'] = 'لم يتم اختيار مؤسسة صحيحة';
$translations['en']['no_org_selected'] = 'No valid organization selected';
$translations['ar']['select_org_instruction'] = 'الرجاء اختيار مؤسسة من القائمة أعلاه أو إدخال كود التحاق صحيح.';
$translations['en']['select_org_instruction'] = 'Please select an organization from the list above or enter a valid invitation code.';
$translations['ar']['org_required_field'] = 'لجهة العمل هذه.';
$translations['en']['org_required_field'] = 'for this organization.';
$translations['ar']['phone_required_org'] = 'رقم الجوال مطلوب إجبارياً لجهة العمل هذه.';
$translations['en']['phone_required_org'] = 'Phone number is required for this organization.';
$translations['ar']['dept_required_org'] = 'القسم مطلوب إجبارياً لجهة العمل هذه.';
$translations['en']['dept_required_org'] = 'Department is required for this organization.';
$translations['ar']['job_required_org'] = 'المسمى الوظيفي مطلوب إجبارياً لجهة العمل هذه.';
$translations['en']['job_required_org'] = 'Job title is required for this organization.';
$translations['ar']['code_invalid'] = 'كود المؤسسة غير صحيح أو غير نشط';
$translations['en']['code_invalid'] = 'Organization code is invalid or inactive';

// Forgot/Reset password translations
$translations['ar']['enter_email_instruction'] = 'أدخل البريد الإلكتروني المرتبط بحسابك.';
$translations['en']['enter_email_instruction'] = 'Enter the email address associated with your account.';
$translations['ar']['send_reset_link'] = 'إرسال رابط إعادة التعيين';
$translations['en']['send_reset_link'] = 'Send Reset Link';
$translations['ar']['reset_link_sent'] = 'إذا كان هناك حساب مرتبط بهذا البريد الإلكتروني، ستتلقى رابط إعادة تعيين كلمة المرور خلال دقائق. تحقق من صندوق الوارد والبريد المزعج (Spam/Junk).';
$translations['en']['reset_link_sent'] = 'If an account exists with that email, you will receive a password reset link within a few minutes. Check your Inbox and Spam/Junk folder.';
$translations['ar']['check_email_instruction'] = 'تحقق من بريدك الإلكتروني للحصول على رابط إعادة تعيين كلمة المرور. الرابط صالح لمدة ساعة واحدة.';
$translations['en']['check_email_instruction'] = 'Check your email for a password reset link. The link expires in 1 hour.';
$translations['ar']['no_account'] = 'Don\'t have an account?';
$translations['en']['no_account'] = 'Don\'t have an account?';
$translations['ar']['password_reset_instruction'] = '8 أحرف على الأقل. استخدم كلمة مرور قوية تحتوي على أحرف كبيرة وصغيرة وأرقام ورموز.';
$translations['en']['password_reset_instruction'] = 'Minimum 8 characters. Use a strong password with uppercase, lowercase, numbers, and symbols.';
$translations['ar']['password_reset_success'] = 'تم إعادة تعيين كلمة المرور بنجاح. يمكنك الآن تسجيل الدخول بكلمة المرور الجديدة.';
$translations['en']['password_reset_success'] = 'Your password has been reset successfully. You can now log in with your new password.';
$translations['ar']['request_reset_link'] = 'يرجى طلب رابط إعادة تعيين كلمة مرور جديد.';
$translations['en']['request_reset_link'] = 'Please request a new password reset link.';
$translations['ar']['enter_valid_email'] = 'يرجى إدخال بريد إلكتروني صحيح.';
$translations['en']['enter_valid_email'] = 'Please enter a valid email address.';

// Email verification translations
$translations['ar']['email_not_found_or_verified'] = 'البريد الإلكتروني غير موجود أو تم التحقق منه بالفعل.';
$translations['en']['email_not_found_or_verified'] = 'Email not found or already verified.';
$translations['ar']['verification_email_sent'] = 'تم إرسال بريد التحقق إلى';
$translations['en']['verification_email_sent'] = 'Verification email has been sent to';
$translations['ar']['check_inbox'] = '. يرجى التحقق من صندوق الوارد والبريد المزعج (Spam/Junk).';
$translations['en']['check_inbox'] = '. Please check your Inbox and Spam/Junk folder.';
$translations['ar']['enter_email_for_verification'] = 'أدخل البريد الإلكتروني المرتبط بحسابك لاستلام رابط التحقق.';
$translations['en']['enter_email_for_verification'] = 'Enter the email address associated with your account to receive a verification link.';
$translations['ar']['didnt_receive_email'] = 'لم تستلم البريد الإلكتروني؟';
$translations['en']['didnt_receive_email'] = 'Didn\'t receive the email?';
$translations['ar']['login_now'] = 'يمكنك الآن تسجيل الدخول.';
$translations['en']['login_now'] = 'You can now proceed to log in.';
$translations['ar']['verification_failed'] = 'فشل إرسال بريد التحقق';
$translations['en']['verification_failed'] = 'Failed to send verification email';

// 2FA verify page
$translations['ar']['code_sent_to_email'] = 'تم إرسال رمز التحقق إلى بريدك الإلكتروني.';
$translations['en']['code_sent_to_email'] = 'A verification code has been sent to your email.';

// Excel export translations
$translations['ar']['export_system_id'] = 'المعرف الخاص';
$translations['en']['export_system_id'] = 'System ID';
$translations['ar']['export_employee_id'] = 'الرقم الوظيفي';
$translations['en']['export_employee_id'] = 'Employee ID';
$translations['ar']['export_full_name'] = 'الاسم الكامل';
$translations['en']['export_full_name'] = 'Full Name';
$translations['ar']['export_department'] = 'القسم';
$translations['en']['export_department'] = 'Department';
$translations['ar']['export_job_title'] = 'المسمى الوظيفي';
$translations['en']['export_job_title'] = 'Job Title';
$translations['ar']['export_hire_date'] = 'تاريخ التوظيف';
$translations['en']['export_hire_date'] = 'Hire Date';
$translations['ar']['export_account_status'] = 'حالة الحساب';
$translations['en']['export_account_status'] = 'Account Status';
$translations['ar']['export_employee_name'] = 'اسم الموظف';
$translations['en']['export_employee_name'] = 'Employee Name';
$translations['ar']['export_leave_type'] = 'نوع الإجازة';
$translations['en']['export_leave_type'] = 'Leave Type';
$translations['ar']['export_from_date'] = 'من تاريخ';
$translations['en']['export_from_date'] = 'From Date';
$translations['ar']['export_to_date'] = 'إلى تاريخ';
$translations['en']['export_to_date'] = 'To Date';
$translations['ar']['export_submitted_on'] = 'تاريخ التقديم';
$translations['en']['export_submitted_on'] = 'Submitted On';
$translations['ar']['export_status'] = 'الحالة';
$translations['en']['export_status'] = 'Status';
$translations['ar']['export_decision_date'] = 'تاريخ القرار';
$translations['en']['export_decision_date'] = 'Decision Date';
$translations['ar']['export_reason'] = 'السبب';
$translations['en']['export_reason'] = 'Reason';
$translations['ar']['export_attachment'] = 'رابط الإثبات';
$translations['en']['export_attachment'] = 'Proof Link';
$translations['ar']['export_request_code'] = 'كود الطلب';
$translations['en']['export_request_code'] = 'Request Code';
$translations['ar']['export_work_days'] = 'أيام العمل الفعلية';
$translations['en']['export_work_days'] = 'Actual Work Days';
$translations['ar']['status_active'] = 'مفعل';
$translations['en']['status_active'] = 'Active';
$translations['ar']['status_rejected'] = 'مرفوض';
$translations['en']['status_rejected'] = 'Rejected';
$translations['ar']['status_pending'] = 'معلق';
$translations['en']['status_pending'] = 'Pending';
$translations['ar']['status_approved_leave'] = 'مقبول';
$translations['en']['status_approved_leave'] = 'Approved';
$translations['ar']['status_rejected_leave'] = 'مرفوضة';
$translations['en']['status_rejected_leave'] = 'Rejected';
$translations['ar']['status_pending_leave'] = 'معلقة';
$translations['en']['status_pending_leave'] = 'Pending';

// Site Health & Diagnostics
$translations['ar']['site_health_title'] = 'فحص صحة النظام';
$translations['en']['site_health_title'] = 'Site Health & Diagnostics';
$translations['ar']['site_health_desc'] = 'لوحة تحكم شاملة للتحقق من حالة النظام والخدمات الحيوية';
$translations['en']['site_health_desc'] = 'Centralized dashboard verifying operational status of all critical services';
$translations['ar']['health_overall_healthy'] = 'النظام سليم';
$translations['en']['health_overall_healthy'] = 'System Healthy';
$translations['ar']['health_overall_warning'] = 'تحذيرات';
$translations['en']['health_overall_warning'] = 'Warnings';
$translations['ar']['health_overall_critical'] = 'أعطال حرجة';
$translations['en']['health_overall_critical'] = 'Critical Issues';
$translations['ar']['health_checks_run'] = 'تم تشغيل %d فحص';
$translations['en']['health_checks_run'] = '%d checks completed';
$translations['ar']['health_app'] = 'التطبيق';
$translations['en']['health_app'] = 'Application';
$translations['ar']['health_db'] = 'قاعدة البيانات';
$translations['en']['health_db'] = 'Database';
$translations['ar']['health_email'] = 'البريد الإلكتروني';
$translations['en']['health_email'] = 'Email';
$translations['ar']['health_auth'] = 'المصادقة';
$translations['en']['health_auth'] = 'Authentication';
$translations['ar']['health_storage'] = 'التخزين';
$translations['en']['health_storage'] = 'Storage';
$translations['ar']['health_routing'] = 'الصفحات والمسارات';
$translations['en']['health_routing'] = 'Routing';
$translations['ar']['health_security'] = 'الأمان';
$translations['en']['health_security'] = 'Security';
$translations['ar']['health_test_email'] = 'اختبار البريد الإلكتروني';
$translations['en']['health_test_email'] = 'Email Test';
$translations['ar']['health_test_email_recipient'] = 'البريد المستلم للاختبار';
$translations['en']['health_test_email_recipient'] = 'Test recipient email';
$translations['ar']['health_send_test'] = 'إرسال اختبار';
$translations['en']['health_send_test'] = 'Send Test';
$translations['ar']['health_diagnostics'] = 'لوحة التشخيص';
$translations['en']['health_diagnostics'] = 'Diagnostics Panel';
$translations['ar']['health_users_today'] = 'مستخدمين اليوم';
$translations['en']['health_users_today'] = 'Users Today';
$translations['ar']['health_pending_leaves'] = 'إجازات معلقة';
$translations['en']['health_pending_leaves'] = 'Pending Leaves';
$translations['ar']['health_pending_employees'] = 'موظفين معلقين';
$translations['en']['health_pending_employees'] = 'Pending Employees';
$translations['ar']['health_email_failures'] = 'فشل البريد';
$translations['en']['health_email_failures'] = 'Email Failures';
$translations['ar']['health_failed_logins'] = 'محاولات فاشلة';
$translations['en']['health_failed_logins'] = 'Failed Logins';
$translations['ar']['health_recent_activity'] = 'أحدث النشاطات';
$translations['en']['health_recent_activity'] = 'Recent Activity';
$translations['ar']['email_not_configured'] = 'البريد الإلكتروني غير مضبوط — يرجى تعيين مفتاح API ومرسل البريد في الإعدادات';
$translations['en']['email_not_configured'] = 'Email not configured — set API key and sender in settings';
$translations['ar']['test_email_sent'] = 'تم إرسال رسالة الاختبار بنجاح';
$translations['en']['test_email_sent'] = 'Test email sent successfully';
$translations['ar']['check_spam'] = 'يرجى التحقق من صندوق الوارد والبريد المزعج (Spam/Junk).';
$translations['en']['check_spam'] = 'Please check your Inbox and Spam/Junk folder.';
$translations['ar']['test_email_failed'] = 'فشل إرسال رسالة الاختبار';
$translations['en']['test_email_failed'] = 'Test email failed';
$translations['ar']['invalid_email'] = 'البريد الإلكتروني غير صالح';
$translations['en']['invalid_email'] = 'Invalid email address';
$translations['ar']['select_org_first'] = 'الرجاء اختيار منشأة أولاً';
$translations['en']['select_org_first'] = 'Please select an organization first';
$translations['ar']['last_checked'] = 'آخر فحص';
$translations['en']['last_checked'] = 'Last checked';
$translations['ar']['refresh'] = 'تحديث';
$translations['en']['refresh'] = 'Refresh';
$translations['ar']['user'] = 'المستخدم';
$translations['en']['user'] = 'User';
$translations['ar']['ip'] = 'IP';
$translations['en']['ip'] = 'IP';

// Super Admin Platform
$translations['ar']['platform_management'] = 'إدارة المنصة';
$translations['en']['platform_management'] = 'Platform Management';
$translations['ar']['system_control'] = 'التحكم في النظام';
$translations['en']['system_control'] = 'System Control';
$translations['ar']['operations'] = 'العمليات';
$translations['en']['operations'] = 'Operations';
$translations['ar']['platform_health'] = 'صحة المنصة';
$translations['en']['platform_health'] = 'Platform Health';
$translations['ar']['healthy'] = 'سليم';
$translations['en']['healthy'] = 'Healthy';
$translations['ar']['configured'] = 'مُعد';
$translations['en']['configured'] = 'Configured';
$translations['ar']['not_configured'] = 'غير مُعد';
$translations['en']['not_configured'] = 'Not Configured';
$translations['ar']['writable'] = 'قابل للكتابة';
$translations['en']['writable'] = 'Writable';
$translations['ar']['session_management'] = 'إدارة الجلسات';
$translations['en']['session_management'] = 'Session Management';
$translations['ar']['file_system'] = 'نظام الملفات';
$translations['en']['file_system'] = 'File System';
$translations['ar']['overall_status'] = 'الحالة العامة';
$translations['en']['overall_status'] = 'Overall Status';
$translations['ar']['top_organizations'] = 'أكبر جهات العمل';
$translations['en']['top_organizations'] = 'Top Organizations';
$translations['ar']['recent_activity'] = 'آخر النشاطات';
$translations['en']['recent_activity'] = 'Recent Activity';
$translations['ar']['view_all'] = 'عرض الكل';
$translations['en']['view_all'] = 'View All';
$translations['ar']['system_settings_table'] = 'جدول إعدادات النظام';
$translations['en']['system_settings_table'] = 'System Settings Table';
$translations['ar']['email_service'] = 'خدمة البريد الإلكتروني';
$translations['en']['email_service'] = 'Email Service';
$translations['ar']['quick_actions'] = 'إجراءات سريعة';
$translations['en']['quick_actions'] = 'Quick Actions';
$translations['ar']['super_admin'] = 'مشرف عام';
$translations['en']['super_admin'] = 'Super Admin';

// Database Migration Center
$translations['ar']['db_migration_center'] = 'ترحيل قاعدة البيانات';
$translations['en']['db_migration_center'] = 'Database Migration Center';
$translations['ar']['db_migration_desc'] = 'إدارة وتنفيذ تحديثات قاعدة البيانات بشكل آمن ومتحكم به';
$translations['en']['db_migration_desc'] = 'Safely manage and execute versioned database updates';
$translations['ar']['migration_dashboard'] = 'لوحة الترحيل';
$translations['en']['migration_dashboard'] = 'Migration Dashboard';
$translations['ar']['current_db_version'] = 'إصدار قاعدة البيانات الحالي';
$translations['en']['current_db_version'] = 'Current Database Version';
$translations['ar']['pending_migrations'] = 'تحديثات معلقة';
$translations['en']['pending_migrations'] = 'Pending Migrations';
$translations['ar']['applied_migrations'] = 'تحديثات مطبقة';
$translations['en']['applied_migrations'] = 'Applied Migrations';
$translations['ar']['failed_migrations'] = 'تحديثات فاشلة';
$translations['en']['failed_migrations'] = 'Failed Migrations';
$translations['ar']['last_update'] = 'آخر تحديث';
$translations['en']['last_update'] = 'Last Update';
$translations['ar']['no_pending_migrations'] = 'لا توجد تحديثات معلقة — قاعدة البيانات محدثة';
$translations['en']['no_pending_migrations'] = 'No pending migrations — database is up to date';
$translations['ar']['apply_all'] = 'تطبيق الكل';
$translations['en']['apply_all'] = 'Apply All';
$translations['ar']['apply'] = 'تطبيق';
$translations['en']['apply'] = 'Apply';
$translations['ar']['rollback'] = 'تراجع';
$translations['en']['rollback'] = 'Rollback';
$translations['ar']['migration_history'] = 'سجل التحديثات';
$translations['en']['migration_history'] = 'Migration History';
$translations['ar']['migration_version'] = 'الإصدار';
$translations['en']['migration_version'] = 'Version';
$translations['ar']['migration_name'] = 'الاسم';
$translations['en']['migration_name'] = 'Name';
$translations['ar']['migration_status'] = 'الحالة';
$translations['en']['migration_status'] = 'Status';
$translations['ar']['migration_output'] = 'المخرجات';
$translations['en']['migration_output'] = 'Output';
$translations['ar']['migration_duration'] = 'المدة';
$translations['en']['migration_duration'] = 'Duration';
$translations['ar']['migration_executed_by'] = 'المنفذ';
$translations['en']['migration_executed_by'] = 'Executed By';
$translations['ar']['migration_executed_at'] = 'تاريخ التنفيذ';
$translations['en']['migration_executed_at'] = 'Executed At';
$translations['ar']['migration_checksum'] = 'المجموع الاختباري';
$translations['en']['migration_checksum'] = 'Checksum';
$translations['ar']['migration_integrity'] = 'السلامة';
$translations['en']['migration_integrity'] = 'Integrity';
$translations['ar']['integrity_pass'] = 'سليم';
$translations['en']['integrity_pass'] = 'Pass';
$translations['ar']['integrity_fail'] = 'تالف — تم تعديل الملف';
$translations['en']['integrity_fail'] = 'Tampered — file content changed';
$translations['ar']['integrity_unknown'] = 'غير متاح';
$translations['en']['integrity_unknown'] = 'Unknown';
$translations['ar']['preflight_check'] = 'فحص ما قبل التحديث';
$translations['en']['preflight_check'] = 'Preflight Check';
$translations['ar']['preflight_pass'] = 'كل الفحوصات سليمة — النظام جاهز للتحديث';
$translations['en']['preflight_pass'] = 'All checks passed — system ready for migration';
$translations['ar']['preflight_warn'] = 'توجد تحذيرات — يرجى المراجعة قبل التحديث';
$translations['en']['preflight_warn'] = 'Warnings detected — review before proceeding';
$translations['ar']['preflight_fail'] = 'فشلت الفحوصات الأولية — لا يمكن التحديث';
$translations['en']['preflight_fail'] = 'Preflight checks failed — cannot proceed';
$translations['ar']['preflight_required'] = 'يجب تشغيل فحص ما قبل التحديث أولاً';
$translations['en']['preflight_required'] = 'Run preflight check before proceeding';
$translations['ar']['preflight_no_issues'] = 'لا توجد مشاكل';
$translations['en']['preflight_no_issues'] = 'No issues';
$translations['ar']['migration_safety'] = 'السلامة والأمان';
$translations['en']['migration_safety'] = 'Safety & Security';
$translations['ar']['safety_backup'] = 'النسخ الاحتياطي';
$translations['ar']['safety_backup_desc'] = 'تأكد من وجود نسخة احتياطية حديثة لقاعدة البيانات قبل التحديث';
$translations['en']['safety_backup'] = 'Backup';
$translations['en']['safety_backup_desc'] = 'Ensure a recent database backup exists before migration';
$translations['ar']['confirm_migration'] = 'تأكيد التحديث';
$translations['en']['confirm_migration'] = 'Confirm Migration';
$translations['ar']['confirm_migration_text'] = 'هل أنت متأكد من تطبيق التحديثات على قاعدة البيانات؟ سيتم تسجيل كل الإجراءات.';
$translations['en']['confirm_migration_text'] = 'Are you sure you want to apply database migrations? All actions are logged.';
$translations['ar']['confirm_rollback_text'] = 'هل أنت متأكد من التراجع عن هذا التحديث؟';
$translations['en']['confirm_rollback_text'] = 'Are you sure you want to rollback this migration?';
$translations['ar']['migration_success'] = 'تم تطبيق التحديث بنجاح';
$translations['en']['migration_success'] = 'Migration applied successfully';
$translations['ar']['migration_failed'] = 'فشل التحديث';
$translations['en']['migration_failed'] = 'Migration failed';
$translations['ar']['migration_applied_all'] = 'تم تطبيق %d من أصل %d تحديث بنجاح';
$translations['en']['migration_applied_all'] = 'Applied %d of %d migrations successfully';
$translations['ar']['rollback_success'] = 'تم التراجع عن التحديث بنجاح';
$translations['en']['rollback_success'] = 'Rollback completed successfully';
$translations['ar']['rollback_failed'] = 'فشل التراجع عن التحديث';
$translations['en']['rollback_failed'] = 'Rollback failed';
$translations['ar']['migration_in_progress'] = 'جاري تطبيق التحديثات...';
$translations['en']['migration_in_progress'] = 'Applying migrations...';
$translations['ar']['run_preflight'] = 'تشغيل الفحص';
$translations['en']['run_preflight'] = 'Run Preflight';
$translations['ar']['preflight_success'] = 'تم تشغيل فحص ما قبل التحديث بنجاح';
$translations['en']['preflight_success'] = 'Preflight check completed';
$translations['ar']['integrity_check'] = 'فحص السلامة';
$translations['en']['integrity_check'] = 'Integrity Check';
$translations['ar']['no_rollback'] = 'لا يوجد نص تراجع';
$translations['en']['no_rollback'] = 'No rollback available';
$translations['ar']['migration_not_applied'] = 'لم يتم تطبيقه بعد';
$translations['en']['migration_not_applied'] = 'Not yet applied';

return $translations;
?>
