<?php
$translations = [
    'ar' => [
        'site_name' => '🏢 نظام إدارة الموظفين',
        'login' => '🔐 تسجيل الدخول',
        'logout' => '🚪 تسجيل الخروج',
        'username' => '👤 اسم المستخدم',
        'password' => '🔑 كلمة المرور',
        'email' => '📧 البريد الإلكتروني',
        'role' => '🛡️ الصلاحية',
        'dashboard' => '📊 لوحة التحكم',
        'employees' => '👥 إدارة الموظفين',
        'approvals' => '✅ طلبات الاعتماد',
        'leaves' => '📅 إدارة الإجازات',
        'my_profile' => '👤 ملفي الشخصي',
        'my_requests' => '📝 طلباتي',
        'system_users' => '💻 مستخدمي النظام',
        'departments' => '🏢 إدارة الأقسام',
        'leave_types' => '🏖️ أنواع الإجازات',
        'welcome' => '👋 مرحباً',
        'total_employees' => '👥 إجمالي الموظفين',
        'pending_approvals' => '⏳ بانتظار الاعتماد',
        'pending_leaves' => '⏳ إجازات معلقة',
        'approved_leaves' => '✅ إجازات مقبولة',
        'my_pending_leaves' => '⏳ إجازاتي المعلقة',
        'my_approved_leaves' => '✅ إجازاتي المقبولة',
        'add_new' => '➕ إضافة جديد',
        'edit' => '✏️ تعديل',
        'delete' => '🗑️ حذف',
        'save' => '💾 حفظ التغييرات',
        'cancel' => '✖️ إلغاء',
        'actions' => '⚙️ الإجراءات',
        'status' => '📍 الحالة',
        'full_name' => '👤 الاسم الكامل',
        'phone' => '📞 رقم الجوال',
        'job_title' => '💼 المسمى الوظيفي',
        'hire_date' => '📅 تاريخ التوظيف',
        'department' => '🏢 القسم',
        'employee_id' => '🆔 الرقم الوظيفي',
        'pending' => '⏳ معلق',
        'approved' => '✅ معتمد',
        'rejected' => '❌ مرفوض',
        'reason' => '💬 السبب',
        'notes' => '📝 ملاحظات المدير',
        'start_date' => '📅 تاريخ البداية',
        'end_date' => '📅 تاريخ النهاية',
        'duration' => '⏱️ المدة',
        'days' => 'أيام',
        'submit' => '🚀 إرسال',
        'close' => '✖️ إغلاق',
        'error_login' => '❌ اسم المستخدم أو كلمة المرور غير صحيحة.',
        'success_added' => '✅ تمت الإضافة بنجاح.',
        'success_updated' => '✅ تم التحديث بنجاح.',
        'confirm_delete' => '⚠️ هل أنت متأكد من الحذف؟',
        'no_data' => '🚫 لا توجد بيانات حالياً.',
        'view' => '👁️ عرض',
        'details' => '📄 التفاصيل',
        'account_info' => '🔐 بيانات الحساب',
        'basic_info' => '📋 البيانات الأساسية',
        'rejection_reason' => '❌ سبب الرفض',
        'decision_date' => '📅 تاريخ القرار',
        'approve' => '✅ موافقة',
        'reject' => '❌ رفض',
        'leave_details' => '🏖️ تفاصيل الإجازة',
        'new_request' => '➕ طلب جديد',
        'manager_note' => '📝 ملاحظة المدير',
        'add_department' => '➕ إضافة قسم',
        'edit_department' => '✏️ تعديل قسم',
        'dept_name' => '🏢 اسم القسم (عربي)',
        'dept_name_en' => '🏢 اسم القسم (EN)',
        'add_leave_type' => '➕ إضافة نوع إجازة',
        'edit_leave_type' => '✏️ تعديل نوع إجازة',
        'type_name' => '🏖️ مسمى الإجازة (عربي)',
        'type_name_en' => '🏖️ مسمى الإجازة (EN)',
        'user_management' => '👥 إدارة المستخدمين',
        'add_user' => '➕ إضافة مستخدم',
        'admin' => '👑 مدير نظام',
        'manager' => '👨‍💼 مدير',
        'employee' => '👨‍🔧 موظف',
        'db_error' => '🔌 خطأ في الاتصال بقاعدة البيانات',
        'access_denied' => '🚫 عذراً، ليس لديك صلاحية للوصول إلى هذه الصفحة.',
        'register' => '📝 طلب تسجيل جديد',
        'already_have_account' => '💡 لديك حساب بالفعل؟',
        'dont_have_account' => '❓ ليس لديك حساب؟',
        'registration_success' => '🎉 تم تقديم طلب التسجيل بنجاح، يرجى انتظار اعتماد الإدارة.',
        'all_rights' => 'حقوق النشر محفوظة',
        'top_leave_types' => '🏖️ أكثر أنواع الإجازات طلباً',
        'top_employees_leaves' => '👥 الموظفين الأكثر طلباً للإجازات',
        'requests' => 'طلبات',
        'leave_stats' => '📊 إحصائيات الإجازات',
        'monthly_requests' => '📈 الطلبات الشهرية',
        'approved_vs_rejected' => '⚖️ المقبولة مقابل المرفوضة',
        'system_id' => '🆔 معرف النظام',
        'initial_balance' => '💰 رصيد الإجازات الحالي',
        'balance_verified' => '✅ تم تأكيد الرصيد',
        'operation_code' => '🔢 كود العملية',
        'operation_time' => '⏰ وقت العملية',
        'verify_balance' => '✅ تأكيد رصيد الإجازات',
        'language' => 'English 🇺🇸',
        'notifications' => '🔔 الإشعارات',
        'mark_as_read' => '👁️ تحديد كمقروء',
        'no_notifications' => '📭 لا توجد إشعارات جديدة',
        'new_leave_request' => '📩 طلب إجازة جديد من',
        'leave_request_approved' => '✅ تمت الموافقة على طلب إجازتك',
        'leave_request_rejected' => '❌ تم رفض طلب إجازتك',
        'profile_approved' => '🎊 تم اعتماد ملفك الوظيفي، يمكنك الآن استخدام النظام بالكامل',
        'activity_log' => '📜 سجل النشاطات',
        'action' => '🎬 الإجراء',
        'ip_address' => '🌐 عنوان IP',
        'user_agent' => '💻 المتصفح/النظام',
        'time' => '⏰ الوقت',
        'settings' => '⚙️ الإعدادات',
        'general_settings' => '⚙️ الإعدادات العامة',
        'ui_settings' => '🎨 إعدادات الواجهة',
        'functional_settings' => '🛠️ الإعدادات الوظيفية',
        'primary_color' => '🎨 اللون الأساسي',
        'font_family' => '🔡 نوع الخط',
        'allow_registration' => '📝 تفعيل التسجيل',
        'allow_leave_requests' => '🏖️ تفعيل طلب الإجازات (للجميع)',
        'footer_text' => '📝 نص الفوتر',
        'on' => 'تشغيل',
        'off' => 'إيقاف',
        'save_settings' => '💾 حفظ الإعدادات',
        'registration_disabled' => '🚫 عذراً، التسجيل متوقف حالياً.',
        'leave_requests_disabled' => '🚫 عذراً، طلب الإجازات متوقف حالياً.',
        'leave_requests_disabled_for_you' => '🚫 عذراً، لقد تم إيقاف صلاحية طلب الإجازات لحسابك مؤقتاً.',
        'balance_not_verified_error' => '🚫 لا يمكنك تقديم طلب إجازة حتى يتم تسجيل رصيدك وتأكيده من قبل المدير.',
        'leave_days_count' => 'عدد أيام الإجازة',
        'security_note_balance' => '⚠️ ملاحظة أمان: لا يمكن تعديل الرصيد المعتمد إلا من قبل المدير.',
        'manager_only_fields' => '🔒 بيانات يتحكم بها المدير فقط',
        'deduct_from_balance' => 'يخصم من الرصيد',
        'max_days_per_year' => 'الحد الأقصى (سنوياً)',
        'yes' => 'نعم',
        'no' => 'لا',
        'insufficient_balance' => '🚫 رصيدك الحالي غير كافٍ لطلب هذه الإجازة.',
        'max_days_per_year_error' => '🚫 تجاوزت الحد الأقصى المسموح به لهذه الإجازة',
        'dir' => 'rtl',
        
        'employee_not_found' => '🚫 الموظف غير موجود.',
        'per_type' => '(لكل نوع)',
        'initial_balances_per_type' => 'رصيد الإجازات المبدئي (لكل نوع)',
        'initial_leave_balances' => 'أرصدة الإجازات المبدئية',
        'ensure_balance_verified' => 'يرجى التأكد من تسجيل رصيد الإجازات في ملفك الشخصي وانتظار اعتماد المدير.',
        'calendar_days' => 'أيام تقويمية',
        'total_balance' => 'إجمالي الرصيد',
        'enter_balance_accurately' => 'يرجى إدخال رصيدك الحالي بدقة لكل نوع، سيتم التحقق منه من قبل الإدارة.',
        'balance_details' => 'تفاصيل الأرصدة',
        'can_edit_balance_before_verification' => 'يمكنك تعديل رصيدك الأولي من خلال زر التعديل أعلاه قبل أن يتم تأكيده من الإدارة.',
        
        'you_have_total' => 'لديك رصيد إجازات إجمالي يبلغ',
        'days_of_leave' => 'يوم',
        'distributed_as_follows' => 'وهي مقسمة حسب الأنواع كالتالي',
        
        'request_dates' => 'تواريخ الطلب',
        'submitted_on' => 'وقت التقديم',
        'decided_on' => 'وقت القرار',
        
        'search_by_employee' => 'بحث بالموظف',
        'employee_name_or_id' => 'اسم أو رقم وظيفي',
        'leave_status' => 'حالة الطلب',
        'all' => 'الكل',
        'filter_btn' => 'تصفية',
        'export_excel' => 'تصدير إكسل',
        'leave_type_label' => 'نوع الإجازة',
        'global_search' => 'بحث شامل',
        'search_placeholder' => 'الاسم، الرقم الوظيفي، أو المعرف',
        'account_status' => 'حالة الحساب',
        'switch_org_desc' => 'يمكنك اختيار وتحديد جهة العمل النشطة من القائمة العلوية لإدارة موظفيها، إجازاتها، وإعداداتها بالكامل وكأنك رئيسها التنفيذي!',
        'quick_actions_center' => '⚡ مركز الإجراءات السريعة (طلبات الإجازة المعلقة)',
        'needs_decision' => 'طلبات تحتاج اتخاذ قرار',
        'employee_label' => 'الموظف',
        'leave_dates' => 'تاريخ الإجازة',
        'work_days' => 'أيام العمل',
        'manager_note_optional' => 'ملاحظة المدير (اختياري)',
        'write_note' => 'اكتب ملاحظة...',
        'quick_decision' => 'اتخاذ قرار فوري',
        'all_departments' => 'جميع الأقسام',
        'lang_code' => 'ar'
    ],
    'en' => [
        'switch_org_desc' => 'You can select and switch active organizations from the top menu to manage their employees, leaves, and settings completely as if you were their CEO!',
        'quick_actions_center' => '⚡ Quick Actions Center (Pending Leave Requests)',
        'needs_decision' => 'requests need a decision',
        'employee_label' => 'Employee',
        'leave_dates' => 'Leave Dates',
        'work_days' => 'Work Days',
        'manager_note_optional' => 'Manager Note (Optional)',
        'write_note' => 'Write a note...',
        'quick_decision' => 'Quick Decision',
        'db_error' => '🔌 Database Connection Error',
        'access_denied' => '🚫 Sorry, you do not have permission to access this page.',
        'register' => '📝 Request Registration',
        'already_have_account' => '💡 Already have an account?',
        'dont_have_account' => "❓ Don't have an account?",
        'registration_success' => '🎉 Registration request submitted successfully, please wait for management approval.',
        'all_rights' => 'All Rights Reserved',
        'top_leave_types' => '🏖️ Most Requested Leave Types',
        'top_employees_leaves' => '👥 Top Employees by Leave Requests',
        'requests' => 'Requests',
        'leave_stats' => '📊 Leave Statistics',
        'monthly_requests' => '📈 Monthly Requests',
        'approved_vs_rejected' => '⚖️ Approved vs Rejected',
        'language' => 'العربية 🇸🇦',
        'notifications' => '🔔 Notifications',
        'mark_as_read' => '👁️ Mark as Read',
        'no_notifications' => '📭 No new notifications',
        'new_leave_request' => '📩 New leave request from',
        'leave_request_approved' => '✅ Your leave request has been approved',
        'leave_request_rejected' => '❌ Your leave request has been rejected',
        'profile_approved' => '🎊 Your profile has been approved, you can now use the system',
        'activity_log' => '📜 Activity Log',
        'action' => '🎬 Action',
        'ip_address' => '🌐 IP Address',
        'user_agent' => '💻 Browser/OS',
        'time' => '⏰ Time',
        'site_name' => '🏢 HR Management System',
        'login' => '🔐 Login',
        'logout' => '🚪 Logout',
        'username' => '👤 Username',
        'password' => '🔑 Password',
        'email' => '📧 Email',
        'role' => '🛡️ Role',
        'dashboard' => '📊 Dashboard',
        'employees' => '👥 Employees Management',
        'approvals' => '✅ Approval Requests',
        'leaves' => '📅 Leave Management',
        'my_profile' => '👤 My Profile',
        'my_requests' => '📝 My Requests',
        'system_users' => '💻 System Users',
        'departments' => '🏢 Departments',
        'leave_types' => '🏖️ Leave Types',
        'welcome' => '👋 Welcome',
        'total_employees' => '👥 Total Employees',
        'pending_approvals' => '⏳ Pending Approvals',
        'pending_leaves' => '⏳ Pending Leaves',
        'approved_leaves' => '✅ Approved Leaves',
        'my_pending_leaves' => '⏳ My Pending Leaves',
        'my_approved_leaves' => '✅ My Approved Leaves',
        'add_new' => '➕ Add New',
        'edit' => '✏️ Edit',
        'delete' => '🗑️ Delete',
        'save' => '💾 Save Changes',
        'cancel' => '✖️ Cancel',
        'actions' => '⚙️ Actions',
        'status' => '📍 Status',
        'full_name' => '👤 Full Name',
        'phone' => '📞 Phone',
        'job_title' => '💼 Job Title',
        'hire_date' => '📅 Hire Date',
        'department' => '🏢 Department',
        'employee_id' => '🆔 Employee ID',
        'pending' => '⏳ Pending',
        'approved' => '✅ Approved',
        'rejected' => '❌ Rejected',
        'reason' => '💬 Reason',
        'notes' => '📝 Manager Notes',
        'start_date' => '📅 Start Date',
        'end_date' => '📅 End Date',
        'duration' => '⏱️ Duration',
        'days' => 'Days',
        'submit' => '🚀 Submit',
        'close' => '✖️ Close',
        'error_login' => '❌ Invalid username or password.',
        'success_added' => '✅ Added successfully.',
        'success_updated' => '✅ Updated successfully.',
        'confirm_delete' => '⚠️ Are you sure you want to delete?',
        'no_data' => '🚫 No data found.',
        'view' => '👁️ View',
        'details' => '📄 Details',
        'account_info' => '🔐 Account Info',
        'basic_info' => '📋 Basic Info',
        'rejection_reason' => '❌ Rejection Reason',
        'decision_date' => '📅 Decision Date',
        'approve' => '✅ Approve',
        'reject' => '❌ Reject',
        'leave_details' => '🏖️ Leave Details',
        'new_request' => '➕ New Request',
        'manager_note' => '📝 Manager Note',
        'dept_name' => '🏢 Dept Name (AR)',
        'dept_name_en' => '🏢 Dept Name (EN)',
        'add_department' => '➕ Add Department',
        'edit_department' => '✏️ Edit Department',
        'add_leave_type' => '➕ Add Leave Type',
        'edit_leave_type' => '✏️ Edit Leave Type',
        'type_name' => '🏖️ Type Name (AR)',
        'type_name_en' => '🏖️ Type Name (EN)',
        'user_management' => '👥 User Management',
        'add_user' => '➕ Add User',
        'admin' => '👑 Admin',
        'manager' => '👨‍💼 Manager',
        'employee' => '👨‍🔧 Employee',
        'system_id' => '🆔 System ID',
        'initial_balance' => '💰 Current Leave Balance',
        'balance_verified' => '✅ Balance Verified',
        'operation_code' => '🔢 Operation Code',
        'operation_time' => '⏰ Operation Time',
        'verify_balance' => '✅ Verify Leave Balance',
        'settings' => '⚙️ Settings',
        'general_settings' => '⚙️ General Settings',
        'ui_settings' => '🎨 UI Settings',
        'functional_settings' => '🛠️ Functional Settings',
        'primary_color' => '🎨 Primary Color',
        'font_family' => '🔡 Font Family',
        'allow_registration' => '📝 Enable Registration',
        'allow_leave_requests' => '🏖️ Enable Leave Requests (Global)',
        'footer_text' => '📝 Footer Text',
        'on' => 'ON',
        'off' => 'OFF',
        'save_settings' => '💾 Save Settings',
        'registration_disabled' => '🚫 Sorry, registration is currently disabled.',
        'leave_requests_disabled' => '🚫 Sorry, leave requests are currently disabled.',
        'leave_requests_disabled_for_you' => '🚫 Sorry, leave requests are temporarily disabled for your account.',
        'balance_not_verified_error' => '🚫 You cannot request leave until your balance is recorded and verified by the manager.',
        'leave_days_count' => 'Number of Leave Days',
        'security_note_balance' => '⚠️ Security Note: Verified balance can only be changed by manager.',
        'manager_only_fields' => '🔒 Fields managed by Manager only',
        'deduct_from_balance' => 'Deduct from Balance',
        'max_days_per_year' => 'Max Days (Yearly)',
        'yes' => 'Yes',
        'no' => 'No',
        'insufficient_balance' => '🚫 Your current balance is insufficient for this request.',
        'max_days_per_year_error' => '🚫 Exceeded the maximum allowed days for this leave type',
        'dir' => 'ltr',
        
        'employee_not_found' => '🚫 Employee not found.',
        'per_type' => '(Per Type)',
        'initial_balances_per_type' => 'Initial Leave Balances (Per Type)',
        'initial_leave_balances' => 'Initial Leave Balances',
        'ensure_balance_verified' => 'Please ensure your leave balance is recorded in your profile and verified by the manager.',
        'calendar_days' => 'Calendar Days',
        'total_balance' => 'Total Balance',
        'enter_balance_accurately' => 'Please enter your current balance accurately for each type; it will be verified by administration.',
        'balance_details' => 'Balance Details',
        'can_edit_balance_before_verification' => 'You can edit your initial balance using the edit button above before it is verified by administration.',
        
        'you_have_total' => 'You have a total leave balance of',
        'days_of_leave' => 'days',
        'distributed_as_follows' => 'distributed by type as follows',
        
        'request_dates' => 'Request Dates',
        'submitted_on' => 'Submitted On',
        'decided_on' => 'Decided On',
        
        'search_by_employee' => 'Search by Employee',
        'employee_name_or_id' => 'Name or ID',
        'leave_status' => 'Leave Status',
        'all' => 'All',
        'filter_btn' => 'Filter',
        'export_excel' => 'Export Excel',
        'leave_type_label' => 'Leave Type',
        'global_search' => 'Global Search',
        'search_placeholder' => 'Name, ID, or System ID',
        'account_status' => 'Account Status',
        'all_departments' => 'All Departments',
        'lang_code' => 'en'
    ]
];

$translations['ar']['prevent_overlapping_leaves'] = 'منع تداخل الإجازات';
$translations['en']['prevent_overlapping_leaves'] = 'Prevent Overlapping Leaves';
$translations['ar']['allow_past_leaves'] = 'السماح بتقديم إجازة بأثر رجعي (تواريخ سابقة)';
$translations['en']['allow_past_leaves'] = 'Allow Retroactive Leaves (Past Dates)';
$translations['ar']['past_leaves_error'] = 'عذراً، غير مسموح بتقديم طلب إجازة في تاريخ قد مضى.';
$translations['en']['past_leaves_error'] = 'Sorry, requesting a leave in the past is not allowed.';

// Settings titles
$translations['ar']['leave_controls'] = 'ضوابط وأنظمة الإجازات';
$translations['en']['leave_controls'] = 'Leave Policies & Controls';

$translations['ar']['overlapping_leaves_error'] = 'عذراً، يوجد لديك إجازة سابقة (معلقة أو مقبولة) تتداخل مع هذه التواريخ.';
$translations['en']['overlapping_leaves_error'] = 'Sorry, you have a previous leave (pending or approved) that overlaps with these dates.';

// 2FA translations
$translations['ar']['security_settings'] = '🔒 إعدادات الأمان';
$translations['en']['security_settings'] = '🔒 Security Settings';
$translations['ar']['2fa_title'] = 'التحقق الثنائي باستخدام تطبيق (2FA)';
$translations['en']['2fa_title'] = 'Two-Factor Authentication (2FA)';
$translations['ar']['2fa_active_title'] = 'ميزة التحقق الثنائي نشطة حالياً لحماية حسابك!';
$translations['en']['2fa_active_title'] = 'Two-Factor Authentication is currently active!';
$translations['ar']['2fa_active_desc'] = 'في كل مرة تقوم فيها بتسجيل الدخول، سيُطلب منك إدخال رمز التحقق المكون من 6 أرقام من تطبيق Authenticator الخاص بك.';
$translations['en']['2fa_active_desc'] = 'Each time you login, you will be required to enter the 6-digit verification code from your Authenticator app.';
$translations['ar']['2fa_disable_title'] = 'تعطيل التحقق الثنائي';
$translations['en']['2fa_disable_title'] = 'Disable Two-Factor Authentication';
$translations['ar']['2fa_disable_desc'] = 'لتعطيل هذه الميزة الأمنية، يرجى إدخال الرمز الحالي من تطبيق التحقق للـتأكيد:';
$translations['en']['2fa_disable_desc'] = 'To disable this security feature, please enter the current code from your Authenticator app to confirm:';
$translations['ar']['2fa_disable_btn'] = '🔴 تعطيل التحقق الثنائي';
$translations['en']['2fa_disable_btn'] = '🔴 Disable Two-Factor Authentication';
$translations['ar']['2fa_setup_title'] = 'إعداد التحقق الثنائي (2FA)';
$translations['en']['2fa_setup_title'] = 'Setup Two-Factor Authentication (2FA)';
$translations['ar']['2fa_setup_desc'] = 'التحقق الثنائي يضيف طبقة أمان إضافية لحسابك. تحتاج لتنزيل تطبيق مثل Google Authenticator أو Authy على هاتفك المحمول أولاً.';
$translations['en']['2fa_setup_desc'] = '2FA adds an extra layer of security. You need to download Google Authenticator or Authy on your mobile phone first.';
$translations['ar']['2fa_step_1'] = '1. امسح الرمز المربع (QR Code)';
$translations['en']['2fa_step_1'] = '1. Scan the QR Code';
$translations['ar']['2fa_step_1_desc'] = 'افتح تطبيق التحقق على هاتفك، واختر "إضافة حساب" ثم قم بمسح الرمز المربع أدناه كاملاً بالعدسة.';
$translations['en']['2fa_step_1_desc'] = 'Open the authenticator app, choose "Add account" and scan the QR code below.';
$translations['ar']['2fa_step_2'] = 'أو أدخل المفتاح السري يدوياً:';
$translations['en']['2fa_step_2'] = 'Or enter the secret key manually:';
$translations['ar']['copy'] = 'نسخ المفتاح';
$translations['en']['copy'] = 'Copy Key';
$translations['ar']['copied'] = 'تم النسخ';
$translations['en']['copied'] = 'Copied';
$translations['ar']['2fa_step_3'] = '2. أدخل رمز التحقق للتأكيد وتفعيل الخدمة';
$translations['en']['2fa_step_3'] = '2. Enter the verification code to activate';
$translations['ar']['2fa_code_label'] = 'رمز التحقق (6 أرقام)';
$translations['en']['2fa_code_label'] = 'Verification Code (6-digits)';
$translations['ar']['2fa_enable_btn'] = '🟢 تفعيل التحقق الثنائي';
$translations['en']['2fa_enable_btn'] = '🟢 Enable Two-Factor Authentication';
$translations['ar']['fill_fields_error'] = 'يرجى ملء جميع الحقول المطلوبة.';
$translations['en']['fill_fields_error'] = 'Please fill all required fields.';
$translations['ar']['2fa_enabled_success'] = '🎉 تم تفعيل ميزة التحقق الثنائي بنجاح وحماية حسابك!';
$translations['en']['2fa_enabled_success'] = '🎉 Two-factor authentication enabled successfully!';
$translations['ar']['2fa_disabled_success'] = '⚠️ تم تعطيل التحقق الثنائي بنجاح. حسابك الآن أقل أماناً.';
$translations['en']['2fa_disabled_success'] = '⚠️ Two-factor authentication disabled successfully.';
$translations['ar']['2fa_invalid_code'] = '❌ الرمز المدخل غير صحيح أو انتهت صلاحيته الزمنيّة، يرجى المحاولة مجدداً.';
$translations['en']['2fa_invalid_code'] = '❌ Invalid verification code, please try again.';

// Super Admin translations
$translations['ar']['super_admin_dashboard'] = '👑 لوحة تحكم المدير العام';
$translations['en']['super_admin_dashboard'] = '👑 Super Admin Dashboard';
$translations['ar']['organizations_mgmt'] = '🏢 إدارة جهات العمل';
$translations['en']['organizations_mgmt'] = '🏢 Organizations Management';
$translations['ar']['add_organization'] = '➕ إضافة جهة عمل جديدة';
$translations['en']['add_organization'] = '➕ Add New Organization';
$translations['ar']['edit_organization'] = '✏️ تعديل جهة العمل';
$translations['en']['edit_organization'] = '✏️ Edit Organization';
$translations['ar']['org_name_ar'] = 'اسم جهة العمل (عربي)';
$translations['en']['org_name_ar'] = 'Organization Name (Arabic)';
$translations['ar']['org_name_en'] = 'اسم جهة العمل (EN)';
$translations['en']['org_name_en'] = 'Organization Name (English)';
$translations['ar']['org_slug'] = 'معرف جهة العمل الفريد (Slug)';
$translations['en']['org_slug'] = 'Organization Slug (Unique Key)';
$translations['ar']['org_manager_username'] = 'اسم مستخدم المدير المشرف';
$translations['en']['org_manager_username'] = 'Supervising Manager Username';
$translations['ar']['org_manager_email'] = 'البريد الإلكتروني للمدير';
$translations['en']['org_manager_email'] = 'Manager Email Address';
$translations['ar']['org_manager_password'] = 'كلمة مرور المدير الأولى';
$translations['en']['org_manager_password'] = 'Initial Manager Password';
$translations['ar']['active'] = '🟢 نشط';
$translations['en']['active'] = '🟢 Active';
$translations['ar']['suspended'] = '🔴 معطل';
$translations['en']['suspended'] = '🔴 Suspended';
$translations['ar']['all_organizations'] = 'جميع جهات العمل';
$translations['en']['all_organizations'] = 'All Organizations';
$translations['ar']['org_count'] = 'عدد جهات العمل';
$translations['en']['org_count'] = 'Organizations Count';
$translations['ar']['organization'] = 'جهة العمل';
$translations['en']['organization'] = 'Organization';
$translations['ar']['switch_org'] = '🔁 تغيير جهة العمل النشطة';
$translations['en']['switch_org'] = '🔁 Switch Active Organization';
$translations['ar']['success_org_created'] = '✅ تم إنشاء جهة العمل وحساب المدير بنجاح!';
$translations['en']['success_org_created'] = '✅ Organization and manager account created successfully!';

// Weekend & Holidays & Reports Translations
$translations['ar']['weekend_settings'] = 'إعدادات عطلات نهاية الأسبوع';
$translations['en']['weekend_settings'] = 'Weekend Settings';
$translations['ar']['weekend_days'] = 'أيام نهاية الأسبوع';
$translations['en']['weekend_days'] = 'Weekend Days';
$translations['ar']['holidays'] = '🏖️ العطلات الرسمية';
$translations['en']['holidays'] = '🏖️ Official Holidays';
$translations['ar']['add_holiday'] = 'إضافة عطلة رسمية';
$translations['en']['add_holiday'] = 'Add Official Holiday';
$translations['ar']['holiday_name'] = 'اسم العطلة';
$translations['en']['holiday_name'] = 'Holiday Name';
$translations['ar']['leave_reports'] = '📊 تقارير وتحليلات الإجازات';
$translations['en']['leave_reports'] = '📊 Leave Reports & Analytics';

return $translations;
?>
